// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scc/protos/scc.proto

package scc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageScanner struct {
	NotificationConfigName string                  `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *StorageScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *StorageScanner) Reset()         { *m = StorageScanner{} }
func (m *StorageScanner) String() string { return proto.CompactTextString(m) }
func (*StorageScanner) ProtoMessage()    {}
func (*StorageScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{0}
}

func (m *StorageScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner.Unmarshal(m, b)
}
func (m *StorageScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner.Marshal(b, m, deterministic)
}
func (m *StorageScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner.Merge(m, src)
}
func (m *StorageScanner) XXX_Size() int {
	return xxx_messageInfo_StorageScanner.Size(m)
}
func (m *StorageScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner proto.InternalMessageInfo

func (m *StorageScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *StorageScanner) GetFinding() *StorageScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type StorageScanner_SourceProperties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageScanner_SourceProperties) Reset()         { *m = StorageScanner_SourceProperties{} }
func (m *StorageScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*StorageScanner_SourceProperties) ProtoMessage()    {}
func (*StorageScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{0, 0}
}

func (m *StorageScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner_SourceProperties.Unmarshal(m, b)
}
func (m *StorageScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *StorageScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner_SourceProperties.Merge(m, src)
}
func (m *StorageScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_StorageScanner_SourceProperties.Size(m)
}
func (m *StorageScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner_SourceProperties proto.InternalMessageInfo

func (m *StorageScanner_SourceProperties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type StorageScanner_Finding struct {
	SourceProperties     *StorageScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	ResourceName         string                           `protobuf:"bytes,2,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Category             string                           `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	State                string                           `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StorageScanner_Finding) Reset()         { *m = StorageScanner_Finding{} }
func (m *StorageScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*StorageScanner_Finding) ProtoMessage()    {}
func (*StorageScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{0, 1}
}

func (m *StorageScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner_Finding.Unmarshal(m, b)
}
func (m *StorageScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner_Finding.Marshal(b, m, deterministic)
}
func (m *StorageScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner_Finding.Merge(m, src)
}
func (m *StorageScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_StorageScanner_Finding.Size(m)
}
func (m *StorageScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner_Finding proto.InternalMessageInfo

func (m *StorageScanner_Finding) GetSourceProperties() *StorageScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *StorageScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *StorageScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *StorageScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type FirewallScanner struct {
	NotificationConfigName string                   `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *FirewallScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *FirewallScanner) Reset()         { *m = FirewallScanner{} }
func (m *FirewallScanner) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner) ProtoMessage()    {}
func (*FirewallScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{1}
}

func (m *FirewallScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner.Unmarshal(m, b)
}
func (m *FirewallScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner.Marshal(b, m, deterministic)
}
func (m *FirewallScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner.Merge(m, src)
}
func (m *FirewallScanner) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner.Size(m)
}
func (m *FirewallScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner proto.InternalMessageInfo

func (m *FirewallScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *FirewallScanner) GetFinding() *FirewallScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type FirewallScanner_SourceProperties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Allowed              string   `protobuf:"bytes,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	AllowedIpRange       string   `protobuf:"bytes,3,opt,name=allowedIpRange,proto3" json:"allowedIpRange,omitempty"`
	ActivationTrigger    string   `protobuf:"bytes,4,opt,name=activationTrigger,proto3" json:"activationTrigger,omitempty"`
	SourceRange          string   `protobuf:"bytes,5,opt,name=sourceRange,proto3" json:"sourceRange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallScanner_SourceProperties) Reset()         { *m = FirewallScanner_SourceProperties{} }
func (m *FirewallScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner_SourceProperties) ProtoMessage()    {}
func (*FirewallScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{1, 0}
}

func (m *FirewallScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Unmarshal(m, b)
}
func (m *FirewallScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *FirewallScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner_SourceProperties.Merge(m, src)
}
func (m *FirewallScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Size(m)
}
func (m *FirewallScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner_SourceProperties proto.InternalMessageInfo

func (m *FirewallScanner_SourceProperties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetAllowed() string {
	if m != nil {
		return m.Allowed
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetAllowedIpRange() string {
	if m != nil {
		return m.AllowedIpRange
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetActivationTrigger() string {
	if m != nil {
		return m.ActivationTrigger
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetSourceRange() string {
	if m != nil {
		return m.SourceRange
	}
	return ""
}

type FirewallScanner_Finding struct {
	SourceProperties     *FirewallScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                            `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                            `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FirewallScanner_Finding) Reset()         { *m = FirewallScanner_Finding{} }
func (m *FirewallScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner_Finding) ProtoMessage()    {}
func (*FirewallScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{1, 1}
}

func (m *FirewallScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner_Finding.Unmarshal(m, b)
}
func (m *FirewallScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner_Finding.Marshal(b, m, deterministic)
}
func (m *FirewallScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner_Finding.Merge(m, src)
}
func (m *FirewallScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner_Finding.Size(m)
}
func (m *FirewallScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner_Finding proto.InternalMessageInfo

func (m *FirewallScanner_Finding) GetSourceProperties() *FirewallScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *FirewallScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *FirewallScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *FirewallScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ComputeInstanceScanner struct {
	NotificationConfigName string                          `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *ComputeInstanceScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                        `json:"-"`
	XXX_unrecognized       []byte                          `json:"-"`
	XXX_sizecache          int32                           `json:"-"`
}

func (m *ComputeInstanceScanner) Reset()         { *m = ComputeInstanceScanner{} }
func (m *ComputeInstanceScanner) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner) ProtoMessage()    {}
func (*ComputeInstanceScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{2}
}

func (m *ComputeInstanceScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner.Merge(m, src)
}
func (m *ComputeInstanceScanner) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner.Size(m)
}
func (m *ComputeInstanceScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner proto.InternalMessageInfo

func (m *ComputeInstanceScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *ComputeInstanceScanner) GetFinding() *ComputeInstanceScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type ComputeInstanceScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeInstanceScanner_SourceProperties) Reset() {
	*m = ComputeInstanceScanner_SourceProperties{}
}
func (m *ComputeInstanceScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner_SourceProperties) ProtoMessage()    {}
func (*ComputeInstanceScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{2, 0}
}

func (m *ComputeInstanceScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Merge(m, src)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Size(m)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner_SourceProperties proto.InternalMessageInfo

func (m *ComputeInstanceScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type ComputeInstanceScanner_Finding struct {
	SourceProperties     *ComputeInstanceScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                                   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                                   `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                                   `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *ComputeInstanceScanner_Finding) Reset()         { *m = ComputeInstanceScanner_Finding{} }
func (m *ComputeInstanceScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner_Finding) ProtoMessage()    {}
func (*ComputeInstanceScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{2, 1}
}

func (m *ComputeInstanceScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner_Finding.Merge(m, src)
}
func (m *ComputeInstanceScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Size(m)
}
func (m *ComputeInstanceScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner_Finding proto.InternalMessageInfo

func (m *ComputeInstanceScanner_Finding) GetSourceProperties() *ComputeInstanceScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *ComputeInstanceScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ComputeInstanceScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *ComputeInstanceScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type DatasetScanner struct {
	NotificationConfigName string                  `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *DatasetScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *DatasetScanner) Reset()         { *m = DatasetScanner{} }
func (m *DatasetScanner) String() string { return proto.CompactTextString(m) }
func (*DatasetScanner) ProtoMessage()    {}
func (*DatasetScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{3}
}

func (m *DatasetScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetScanner.Unmarshal(m, b)
}
func (m *DatasetScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetScanner.Marshal(b, m, deterministic)
}
func (m *DatasetScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetScanner.Merge(m, src)
}
func (m *DatasetScanner) XXX_Size() int {
	return xxx_messageInfo_DatasetScanner.Size(m)
}
func (m *DatasetScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetScanner.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetScanner proto.InternalMessageInfo

func (m *DatasetScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *DatasetScanner) GetFinding() *DatasetScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type DatasetScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DatasetScanner_SourceProperties) Reset()         { *m = DatasetScanner_SourceProperties{} }
func (m *DatasetScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*DatasetScanner_SourceProperties) ProtoMessage()    {}
func (*DatasetScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{3, 0}
}

func (m *DatasetScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetScanner_SourceProperties.Unmarshal(m, b)
}
func (m *DatasetScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *DatasetScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetScanner_SourceProperties.Merge(m, src)
}
func (m *DatasetScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_DatasetScanner_SourceProperties.Size(m)
}
func (m *DatasetScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetScanner_SourceProperties proto.InternalMessageInfo

func (m *DatasetScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type DatasetScanner_Finding struct {
	SourceProperties     *DatasetScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                           `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                           `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                           `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *DatasetScanner_Finding) Reset()         { *m = DatasetScanner_Finding{} }
func (m *DatasetScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*DatasetScanner_Finding) ProtoMessage()    {}
func (*DatasetScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{3, 1}
}

func (m *DatasetScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DatasetScanner_Finding.Unmarshal(m, b)
}
func (m *DatasetScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DatasetScanner_Finding.Marshal(b, m, deterministic)
}
func (m *DatasetScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DatasetScanner_Finding.Merge(m, src)
}
func (m *DatasetScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_DatasetScanner_Finding.Size(m)
}
func (m *DatasetScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_DatasetScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_DatasetScanner_Finding proto.InternalMessageInfo

func (m *DatasetScanner_Finding) GetSourceProperties() *DatasetScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *DatasetScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *DatasetScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *DatasetScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type IamScanner struct {
	NotificationConfigName string              `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *IamScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}            `json:"-"`
	XXX_unrecognized       []byte              `json:"-"`
	XXX_sizecache          int32               `json:"-"`
}

func (m *IamScanner) Reset()         { *m = IamScanner{} }
func (m *IamScanner) String() string { return proto.CompactTextString(m) }
func (*IamScanner) ProtoMessage()    {}
func (*IamScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{4}
}

func (m *IamScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner.Unmarshal(m, b)
}
func (m *IamScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner.Marshal(b, m, deterministic)
}
func (m *IamScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner.Merge(m, src)
}
func (m *IamScanner) XXX_Size() int {
	return xxx_messageInfo_IamScanner.Size(m)
}
func (m *IamScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner proto.InternalMessageInfo

func (m *IamScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *IamScanner) GetFinding() *IamScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type IamScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	OffendingIamRoles    string   `protobuf:"bytes,2,opt,name=offendingIamRoles,proto3" json:"offendingIamRoles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IamScanner_SourceProperties) Reset()         { *m = IamScanner_SourceProperties{} }
func (m *IamScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*IamScanner_SourceProperties) ProtoMessage()    {}
func (*IamScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{4, 0}
}

func (m *IamScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner_SourceProperties.Unmarshal(m, b)
}
func (m *IamScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *IamScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner_SourceProperties.Merge(m, src)
}
func (m *IamScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_IamScanner_SourceProperties.Size(m)
}
func (m *IamScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner_SourceProperties proto.InternalMessageInfo

func (m *IamScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *IamScanner_SourceProperties) GetOffendingIamRoles() string {
	if m != nil {
		return m.OffendingIamRoles
	}
	return ""
}

type IamScanner_Finding struct {
	SourceProperties     *IamScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                       `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Parent               string                       `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	State                string                       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	ResourceName         string                       `protobuf:"bytes,5,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *IamScanner_Finding) Reset()         { *m = IamScanner_Finding{} }
func (m *IamScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*IamScanner_Finding) ProtoMessage()    {}
func (*IamScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{4, 1}
}

func (m *IamScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner_Finding.Unmarshal(m, b)
}
func (m *IamScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner_Finding.Marshal(b, m, deterministic)
}
func (m *IamScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner_Finding.Merge(m, src)
}
func (m *IamScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_IamScanner_Finding.Size(m)
}
func (m *IamScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner_Finding proto.InternalMessageInfo

func (m *IamScanner_Finding) GetSourceProperties() *IamScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *IamScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *IamScanner_Finding) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *IamScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *IamScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type SqlScanner struct {
	NotificationConfigName string              `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *SqlScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}            `json:"-"`
	XXX_unrecognized       []byte              `json:"-"`
	XXX_sizecache          int32               `json:"-"`
}

func (m *SqlScanner) Reset()         { *m = SqlScanner{} }
func (m *SqlScanner) String() string { return proto.CompactTextString(m) }
func (*SqlScanner) ProtoMessage()    {}
func (*SqlScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{5}
}

func (m *SqlScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner.Unmarshal(m, b)
}
func (m *SqlScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner.Marshal(b, m, deterministic)
}
func (m *SqlScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner.Merge(m, src)
}
func (m *SqlScanner) XXX_Size() int {
	return xxx_messageInfo_SqlScanner.Size(m)
}
func (m *SqlScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner proto.InternalMessageInfo

func (m *SqlScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *SqlScanner) GetFinding() *SqlScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type SqlScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlScanner_SourceProperties) Reset()         { *m = SqlScanner_SourceProperties{} }
func (m *SqlScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*SqlScanner_SourceProperties) ProtoMessage()    {}
func (*SqlScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{5, 0}
}

func (m *SqlScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner_SourceProperties.Unmarshal(m, b)
}
func (m *SqlScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *SqlScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner_SourceProperties.Merge(m, src)
}
func (m *SqlScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_SqlScanner_SourceProperties.Size(m)
}
func (m *SqlScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner_SourceProperties proto.InternalMessageInfo

func (m *SqlScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type SqlScanner_Finding struct {
	SourceProperties     *SqlScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                       `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                       `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                       `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SqlScanner_Finding) Reset()         { *m = SqlScanner_Finding{} }
func (m *SqlScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*SqlScanner_Finding) ProtoMessage()    {}
func (*SqlScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{5, 1}
}

func (m *SqlScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner_Finding.Unmarshal(m, b)
}
func (m *SqlScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner_Finding.Marshal(b, m, deterministic)
}
func (m *SqlScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner_Finding.Merge(m, src)
}
func (m *SqlScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_SqlScanner_Finding.Size(m)
}
func (m *SqlScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner_Finding proto.InternalMessageInfo

func (m *SqlScanner_Finding) GetSourceProperties() *SqlScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *SqlScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SqlScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *SqlScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type ContainerScanner struct {
	NotificationConfigName string                    `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *ContainerScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                  `json:"-"`
	XXX_unrecognized       []byte                    `json:"-"`
	XXX_sizecache          int32                     `json:"-"`
}

func (m *ContainerScanner) Reset()         { *m = ContainerScanner{} }
func (m *ContainerScanner) String() string { return proto.CompactTextString(m) }
func (*ContainerScanner) ProtoMessage()    {}
func (*ContainerScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{6}
}

func (m *ContainerScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerScanner.Unmarshal(m, b)
}
func (m *ContainerScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerScanner.Marshal(b, m, deterministic)
}
func (m *ContainerScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerScanner.Merge(m, src)
}
func (m *ContainerScanner) XXX_Size() int {
	return xxx_messageInfo_ContainerScanner.Size(m)
}
func (m *ContainerScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerScanner.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerScanner proto.InternalMessageInfo

func (m *ContainerScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *ContainerScanner) GetFinding() *ContainerScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type ContainerScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContainerScanner_SourceProperties) Reset()         { *m = ContainerScanner_SourceProperties{} }
func (m *ContainerScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*ContainerScanner_SourceProperties) ProtoMessage()    {}
func (*ContainerScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{6, 0}
}

func (m *ContainerScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerScanner_SourceProperties.Unmarshal(m, b)
}
func (m *ContainerScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *ContainerScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerScanner_SourceProperties.Merge(m, src)
}
func (m *ContainerScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_ContainerScanner_SourceProperties.Size(m)
}
func (m *ContainerScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerScanner_SourceProperties proto.InternalMessageInfo

func (m *ContainerScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type ContainerScanner_Finding struct {
	SourceProperties     *ContainerScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                             `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                             `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                             `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *ContainerScanner_Finding) Reset()         { *m = ContainerScanner_Finding{} }
func (m *ContainerScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*ContainerScanner_Finding) ProtoMessage()    {}
func (*ContainerScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{6, 1}
}

func (m *ContainerScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerScanner_Finding.Unmarshal(m, b)
}
func (m *ContainerScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerScanner_Finding.Marshal(b, m, deterministic)
}
func (m *ContainerScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerScanner_Finding.Merge(m, src)
}
func (m *ContainerScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_ContainerScanner_Finding.Size(m)
}
func (m *ContainerScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerScanner_Finding proto.InternalMessageInfo

func (m *ContainerScanner_Finding) GetSourceProperties() *ContainerScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *ContainerScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ContainerScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *ContainerScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type LoggingScanner struct {
	NotificationConfigName string                  `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *LoggingScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *LoggingScanner) Reset()         { *m = LoggingScanner{} }
func (m *LoggingScanner) String() string { return proto.CompactTextString(m) }
func (*LoggingScanner) ProtoMessage()    {}
func (*LoggingScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{7}
}

func (m *LoggingScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingScanner.Unmarshal(m, b)
}
func (m *LoggingScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingScanner.Marshal(b, m, deterministic)
}
func (m *LoggingScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingScanner.Merge(m, src)
}
func (m *LoggingScanner) XXX_Size() int {
	return xxx_messageInfo_LoggingScanner.Size(m)
}
func (m *LoggingScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingScanner.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingScanner proto.InternalMessageInfo

func (m *LoggingScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *LoggingScanner) GetFinding() *LoggingScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type LoggingScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoggingScanner_SourceProperties) Reset()         { *m = LoggingScanner_SourceProperties{} }
func (m *LoggingScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*LoggingScanner_SourceProperties) ProtoMessage()    {}
func (*LoggingScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{7, 0}
}

func (m *LoggingScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingScanner_SourceProperties.Unmarshal(m, b)
}
func (m *LoggingScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *LoggingScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingScanner_SourceProperties.Merge(m, src)
}
func (m *LoggingScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_LoggingScanner_SourceProperties.Size(m)
}
func (m *LoggingScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingScanner_SourceProperties proto.InternalMessageInfo

func (m *LoggingScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type LoggingScanner_Finding struct {
	SourceProperties     *LoggingScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                           `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                           `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                           `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *LoggingScanner_Finding) Reset()         { *m = LoggingScanner_Finding{} }
func (m *LoggingScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*LoggingScanner_Finding) ProtoMessage()    {}
func (*LoggingScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{7, 1}
}

func (m *LoggingScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoggingScanner_Finding.Unmarshal(m, b)
}
func (m *LoggingScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoggingScanner_Finding.Marshal(b, m, deterministic)
}
func (m *LoggingScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoggingScanner_Finding.Merge(m, src)
}
func (m *LoggingScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_LoggingScanner_Finding.Size(m)
}
func (m *LoggingScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_LoggingScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_LoggingScanner_Finding proto.InternalMessageInfo

func (m *LoggingScanner_Finding) GetSourceProperties() *LoggingScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *LoggingScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *LoggingScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *LoggingScanner_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

type AnomalousIAMGrant struct {
	NotificationConfigName string                     `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *AnomalousIAMGrant_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                   `json:"-"`
	XXX_unrecognized       []byte                     `json:"-"`
	XXX_sizecache          int32                      `json:"-"`
}

func (m *AnomalousIAMGrant) Reset()         { *m = AnomalousIAMGrant{} }
func (m *AnomalousIAMGrant) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant) ProtoMessage()    {}
func (*AnomalousIAMGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{8}
}

func (m *AnomalousIAMGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant.Merge(m, src)
}
func (m *AnomalousIAMGrant) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant.Size(m)
}
func (m *AnomalousIAMGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant proto.InternalMessageInfo

func (m *AnomalousIAMGrant) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *AnomalousIAMGrant) GetFinding() *AnomalousIAMGrant_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type AnomalousIAMGrant_SourceProperties struct {
	PropertiesProjectId         string   `protobuf:"bytes,1,opt,name=properties_project_id,json=propertiesProjectId,proto3" json:"properties_project_id,omitempty"`
	PropertiesExternalMembers_0 string   `protobuf:"bytes,2,opt,name=properties_externalMembers_0,json=propertiesExternalMembers0,proto3" json:"properties_externalMembers_0,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *AnomalousIAMGrant_SourceProperties) Reset()         { *m = AnomalousIAMGrant_SourceProperties{} }
func (m *AnomalousIAMGrant_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_SourceProperties) ProtoMessage()    {}
func (*AnomalousIAMGrant_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{8, 0}
}

func (m *AnomalousIAMGrant_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_SourceProperties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_SourceProperties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_SourceProperties.Merge(m, src)
}
func (m *AnomalousIAMGrant_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_SourceProperties.Size(m)
}
func (m *AnomalousIAMGrant_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_SourceProperties proto.InternalMessageInfo

func (m *AnomalousIAMGrant_SourceProperties) GetPropertiesProjectId() string {
	if m != nil {
		return m.PropertiesProjectId
	}
	return ""
}

func (m *AnomalousIAMGrant_SourceProperties) GetPropertiesExternalMembers_0() string {
	if m != nil {
		return m.PropertiesExternalMembers_0
	}
	return ""
}

type AnomalousIAMGrant_Finding struct {
	SourceProperties     *AnomalousIAMGrant_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	ResourceName         string                              `protobuf:"bytes,2,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Category             string                              `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	State                string                              `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *AnomalousIAMGrant_Finding) Reset()         { *m = AnomalousIAMGrant_Finding{} }
func (m *AnomalousIAMGrant_Finding) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_Finding) ProtoMessage()    {}
func (*AnomalousIAMGrant_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_327e9ee15b8f944f, []int{8, 1}
}

func (m *AnomalousIAMGrant_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_Finding.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_Finding.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_Finding.Merge(m, src)
}
func (m *AnomalousIAMGrant_Finding) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_Finding.Size(m)
}
func (m *AnomalousIAMGrant_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_Finding proto.InternalMessageInfo

func (m *AnomalousIAMGrant_Finding) GetSourceProperties() *AnomalousIAMGrant_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *AnomalousIAMGrant_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *AnomalousIAMGrant_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AnomalousIAMGrant_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func init() {
	proto.RegisterType((*StorageScanner)(nil), "StorageScanner")
	proto.RegisterType((*StorageScanner_SourceProperties)(nil), "StorageScanner.SourceProperties")
	proto.RegisterType((*StorageScanner_Finding)(nil), "StorageScanner.Finding")
	proto.RegisterType((*FirewallScanner)(nil), "FirewallScanner")
	proto.RegisterType((*FirewallScanner_SourceProperties)(nil), "FirewallScanner.SourceProperties")
	proto.RegisterType((*FirewallScanner_Finding)(nil), "FirewallScanner.Finding")
	proto.RegisterType((*ComputeInstanceScanner)(nil), "ComputeInstanceScanner")
	proto.RegisterType((*ComputeInstanceScanner_SourceProperties)(nil), "ComputeInstanceScanner.SourceProperties")
	proto.RegisterType((*ComputeInstanceScanner_Finding)(nil), "ComputeInstanceScanner.Finding")
	proto.RegisterType((*DatasetScanner)(nil), "DatasetScanner")
	proto.RegisterType((*DatasetScanner_SourceProperties)(nil), "DatasetScanner.SourceProperties")
	proto.RegisterType((*DatasetScanner_Finding)(nil), "DatasetScanner.Finding")
	proto.RegisterType((*IamScanner)(nil), "IamScanner")
	proto.RegisterType((*IamScanner_SourceProperties)(nil), "IamScanner.SourceProperties")
	proto.RegisterType((*IamScanner_Finding)(nil), "IamScanner.Finding")
	proto.RegisterType((*SqlScanner)(nil), "SqlScanner")
	proto.RegisterType((*SqlScanner_SourceProperties)(nil), "SqlScanner.SourceProperties")
	proto.RegisterType((*SqlScanner_Finding)(nil), "SqlScanner.Finding")
	proto.RegisterType((*ContainerScanner)(nil), "ContainerScanner")
	proto.RegisterType((*ContainerScanner_SourceProperties)(nil), "ContainerScanner.SourceProperties")
	proto.RegisterType((*ContainerScanner_Finding)(nil), "ContainerScanner.Finding")
	proto.RegisterType((*LoggingScanner)(nil), "LoggingScanner")
	proto.RegisterType((*LoggingScanner_SourceProperties)(nil), "LoggingScanner.SourceProperties")
	proto.RegisterType((*LoggingScanner_Finding)(nil), "LoggingScanner.Finding")
	proto.RegisterType((*AnomalousIAMGrant)(nil), "AnomalousIAMGrant")
	proto.RegisterType((*AnomalousIAMGrant_SourceProperties)(nil), "AnomalousIAMGrant.SourceProperties")
	proto.RegisterType((*AnomalousIAMGrant_Finding)(nil), "AnomalousIAMGrant.Finding")
}

func init() { proto.RegisterFile("scc/protos/scc.proto", fileDescriptor_327e9ee15b8f944f) }

var fileDescriptor_327e9ee15b8f944f = []byte{
	// 686 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x97, 0x4f, 0x6e, 0xd3, 0x4e,
	0x14, 0xc7, 0x15, 0xe7, 0xd7, 0xf6, 0xd7, 0x57, 0x54, 0x5a, 0xb7, 0x14, 0x63, 0x55, 0x22, 0x04,
	0x09, 0x75, 0x01, 0x6e, 0x49, 0x11, 0x12, 0x3b, 0xaa, 0x96, 0x82, 0xa5, 0xb6, 0x54, 0x49, 0xd7,
	0x54, 0x53, 0xe7, 0xc5, 0x1a, 0x64, 0xcf, 0x98, 0xf1, 0x84, 0xc2, 0x0d, 0xb8, 0x01, 0x67, 0x60,
	0xc1, 0x9f, 0x0d, 0x6b, 0x04, 0x37, 0xe0, 0x00, 0xac, 0x38, 0x02, 0x62, 0x8f, 0xea, 0x38, 0x89,
	0x33, 0xb6, 0xa5, 0x84, 0x24, 0x78, 0xe7, 0x99, 0x37, 0xf3, 0x7d, 0x9e, 0xcf, 0xf7, 0xf9, 0x69,
	0x0c, 0xab, 0xa1, 0xe3, 0x6c, 0x06, 0x82, 0x4b, 0x1e, 0x6e, 0x86, 0x8e, 0x63, 0x45, 0x8f, 0xd5,
	0x1f, 0x1a, 0x2c, 0x36, 0x24, 0x17, 0xc4, 0xc5, 0x86, 0x43, 0x18, 0x43, 0xa1, 0xdf, 0x87, 0x35,
	0xc6, 0x25, 0x6d, 0x51, 0x87, 0x48, 0xca, 0xd9, 0x2e, 0x67, 0x2d, 0xea, 0x1e, 0x11, 0x1f, 0x8d,
	0x52, 0xa5, 0xb4, 0x31, 0x5f, 0xcf, 0x89, 0xea, 0x77, 0x61, 0xae, 0x45, 0x59, 0x93, 0x32, 0xd7,
	0xd0, 0x2a, 0xa5, 0x8d, 0x85, 0xda, 0x55, 0x6b, 0x50, 0xd9, 0xda, 0xef, 0x84, 0xeb, 0xdd, 0x75,
	0xe6, 0x16, 0x2c, 0x35, 0x78, 0x5b, 0x38, 0x78, 0x2c, 0x78, 0x80, 0x42, 0x52, 0x0c, 0xf5, 0x75,
	0x98, 0x0f, 0x04, 0x7f, 0x8e, 0x8e, 0xb4, 0x9b, 0x71, 0xc6, 0xfe, 0x84, 0xf9, 0xbe, 0x04, 0x73,
	0xb1, 0x8c, 0x7e, 0x00, 0x4b, 0xa1, 0xb2, 0x3b, 0xda, 0xb0, 0x50, 0xab, 0xa8, 0x99, 0xd5, 0x2c,
	0xf5, 0xd4, 0x4e, 0xbd, 0x0a, 0x97, 0x04, 0x76, 0x66, 0xa3, 0xc3, 0x6a, 0x51, 0xea, 0x81, 0x39,
	0xdd, 0x84, 0xff, 0x1d, 0x22, 0xd1, 0xe5, 0xe2, 0xb5, 0x51, 0x8e, 0xe2, 0xbd, 0xb1, 0xbe, 0x0a,
	0x33, 0xa1, 0x24, 0x12, 0x8d, 0xff, 0xa2, 0x40, 0x67, 0x50, 0xfd, 0x55, 0x86, 0xcb, 0xfb, 0x54,
	0xe0, 0x39, 0xf1, 0xbc, 0x71, 0x01, 0xd7, 0x54, 0xc0, 0x86, 0xa5, 0x48, 0xa7, 0x09, 0x7f, 0x2b,
	0x8d, 0x8a, 0x58, 0x37, 0x60, 0x8e, 0x78, 0x1e, 0x3f, 0xc7, 0x66, 0xcc, 0xa0, 0x3b, 0xd4, 0x6f,
	0xc1, 0x62, 0xfc, 0x68, 0x07, 0x75, 0xc2, 0x5c, 0x8c, 0x21, 0x28, 0xb3, 0xfa, 0x6d, 0x58, 0x26,
	0x8e, 0xa4, 0x2f, 0xa3, 0x03, 0x9c, 0x08, 0xea, 0xba, 0x28, 0x62, 0x2c, 0xe9, 0x80, 0x5e, 0x81,
	0x85, 0x0e, 0xe2, 0x8e, 0xe4, 0x4c, 0xb4, 0x2e, 0x39, 0x65, 0x7e, 0x48, 0x98, 0x7e, 0x98, 0x6b,
	0xfa, 0x8d, 0x14, 0x8d, 0x21, 0x5c, 0x4f, 0x3a, 0xaa, 0x29, 0x8e, 0xaa, 0x15, 0x51, 0xce, 0xa8,
	0x88, 0x6c, 0xd7, 0x7f, 0x6b, 0xb0, 0xb6, 0xcb, 0xfd, 0xa0, 0x2d, 0xd1, 0x66, 0xa1, 0x24, 0xcc,
	0x19, 0xfb, 0xeb, 0x7a, 0xa0, 0x9a, 0x7f, 0xdd, 0xca, 0xce, 0x30, 0xf2, 0x57, 0xb6, 0xa7, 0x96,
	0xc0, 0x9e, 0xf9, 0x39, 0x01, 0xfc, 0x24, 0x17, 0xf8, 0x46, 0xde, 0x1b, 0x14, 0xc6, 0xfd, 0xa2,
	0x9b, 0xed, 0x11, 0x49, 0x42, 0x94, 0x53, 0xe8, 0x66, 0x83, 0xca, 0x93, 0xe0, 0x3c, 0x6c, 0x37,
	0x53, 0x32, 0x17, 0xc6, 0xf7, 0x6d, 0x19, 0xc0, 0x26, 0xfe, 0xb8, 0x6c, 0xef, 0xa8, 0x6c, 0x57,
	0xac, 0xbe, 0x6a, 0x9a, 0xeb, 0xb3, 0x51, 0xb9, 0x5e, 0x34, 0x20, 0xde, 0x6a, 0x61, 0xb4, 0xdd,
	0x26, 0x7e, 0x9d, 0x7b, 0x18, 0xc6, 0x18, 0xd2, 0x01, 0xf3, 0x6b, 0xc2, 0x85, 0x27, 0xb9, 0x2e,
	0xac, 0x27, 0xdf, 0x71, 0x4c, 0x07, 0xd6, 0x60, 0x36, 0x20, 0x02, 0x99, 0x8c, 0xd9, 0xc7, 0xa3,
	0x6c, 0xea, 0x29, 0xbf, 0x66, 0xd2, 0x7e, 0x55, 0xbf, 0x6b, 0x00, 0x8d, 0x17, 0xde, 0x14, 0x9c,
	0xe9, 0xab, 0x4e, 0xa2, 0xe2, 0xdf, 0x0d, 0xc9, 0x3a, 0x91, 0xb5, 0xb0, 0x6a, 0xff, 0xa9, 0xc1,
	0xd2, 0x2e, 0x67, 0x92, 0x50, 0x86, 0x62, 0x5c, 0xb2, 0xdb, 0x2a, 0xd9, 0x6b, 0x96, 0xaa, 0x3d,
	0x09, 0xbe, 0x1f, 0x13, 0x7c, 0x8f, 0x72, 0xf9, 0x56, 0xd3, 0xb9, 0x0b, 0xed, 0xd9, 0x07, 0xdc,
	0x75, 0x29, 0x73, 0xa7, 0xd0, 0xb3, 0x07, 0x95, 0xff, 0x65, 0xcf, 0x56, 0x32, 0x17, 0xc6, 0xf7,
	0x4b, 0x19, 0x96, 0x77, 0x18, 0xf7, 0x89, 0xc7, 0xdb, 0xa1, 0xbd, 0x73, 0xf8, 0x58, 0x10, 0x26,
	0xff, 0x1a, 0xf1, 0x3d, 0x15, 0xb1, 0x69, 0xa5, 0xc4, 0xd3, 0x94, 0xdf, 0x64, 0xdd, 0x42, 0x6b,
	0x70, 0x25, 0xe8, 0x8d, 0x4e, 0x63, 0xc0, 0xa7, 0xb4, 0x7b, 0x23, 0x5d, 0xe9, 0x07, 0x8f, 0x7b,
	0x77, 0xd3, 0x87, 0xb0, 0x9e, 0xd8, 0x83, 0xaf, 0x24, 0x0a, 0x46, 0xbc, 0x43, 0xf4, 0xcf, 0x50,
	0x84, 0xa7, 0x5b, 0x31, 0x36, 0xb3, 0xbf, 0xe6, 0xd1, 0xe0, 0x92, 0x2d, 0xf3, 0x53, 0xc2, 0xbe,
	0xa7, 0xb9, 0xf6, 0xdd, 0xcc, 0x38, 0x55, 0x51, 0xff, 0x10, 0x67, 0xb3, 0xd1, 0xaf, 0xda, 0xf6,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x72, 0x1d, 0x74, 0xc2, 0x0d, 0x00, 0x00,
}
