// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sha/protos/sha.proto

package sha

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StorageScanner struct {
	NotificationConfigName string                  `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *StorageScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *StorageScanner) Reset()         { *m = StorageScanner{} }
func (m *StorageScanner) String() string { return proto.CompactTextString(m) }
func (*StorageScanner) ProtoMessage()    {}
func (*StorageScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{0}
}

func (m *StorageScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner.Unmarshal(m, b)
}
func (m *StorageScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner.Marshal(b, m, deterministic)
}
func (m *StorageScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner.Merge(m, src)
}
func (m *StorageScanner) XXX_Size() int {
	return xxx_messageInfo_StorageScanner.Size(m)
}
func (m *StorageScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner proto.InternalMessageInfo

func (m *StorageScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *StorageScanner) GetFinding() *StorageScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type StorageScanner_SourceProperties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StorageScanner_SourceProperties) Reset()         { *m = StorageScanner_SourceProperties{} }
func (m *StorageScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*StorageScanner_SourceProperties) ProtoMessage()    {}
func (*StorageScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{0, 0}
}

func (m *StorageScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner_SourceProperties.Unmarshal(m, b)
}
func (m *StorageScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *StorageScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner_SourceProperties.Merge(m, src)
}
func (m *StorageScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_StorageScanner_SourceProperties.Size(m)
}
func (m *StorageScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner_SourceProperties proto.InternalMessageInfo

func (m *StorageScanner_SourceProperties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type StorageScanner_Finding struct {
	SourceProperties     *StorageScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	ResourceName         string                           `protobuf:"bytes,2,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	Category             string                           `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *StorageScanner_Finding) Reset()         { *m = StorageScanner_Finding{} }
func (m *StorageScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*StorageScanner_Finding) ProtoMessage()    {}
func (*StorageScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{0, 1}
}

func (m *StorageScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorageScanner_Finding.Unmarshal(m, b)
}
func (m *StorageScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorageScanner_Finding.Marshal(b, m, deterministic)
}
func (m *StorageScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorageScanner_Finding.Merge(m, src)
}
func (m *StorageScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_StorageScanner_Finding.Size(m)
}
func (m *StorageScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_StorageScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_StorageScanner_Finding proto.InternalMessageInfo

func (m *StorageScanner_Finding) GetSourceProperties() *StorageScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *StorageScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *StorageScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type FirewallScanner struct {
	NotificationConfigName string                   `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *FirewallScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                 `json:"-"`
	XXX_unrecognized       []byte                   `json:"-"`
	XXX_sizecache          int32                    `json:"-"`
}

func (m *FirewallScanner) Reset()         { *m = FirewallScanner{} }
func (m *FirewallScanner) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner) ProtoMessage()    {}
func (*FirewallScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{1}
}

func (m *FirewallScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner.Unmarshal(m, b)
}
func (m *FirewallScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner.Marshal(b, m, deterministic)
}
func (m *FirewallScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner.Merge(m, src)
}
func (m *FirewallScanner) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner.Size(m)
}
func (m *FirewallScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner proto.InternalMessageInfo

func (m *FirewallScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *FirewallScanner) GetFinding() *FirewallScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type FirewallScanner_SourceProperties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	Allowed              string   `protobuf:"bytes,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	AllowedIpRange       string   `protobuf:"bytes,3,opt,name=allowedIpRange,proto3" json:"allowedIpRange,omitempty"`
	ActivationTrigger    string   `protobuf:"bytes,4,opt,name=activationTrigger,proto3" json:"activationTrigger,omitempty"`
	SourceRange          string   `protobuf:"bytes,5,opt,name=sourceRange,proto3" json:"sourceRange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FirewallScanner_SourceProperties) Reset()         { *m = FirewallScanner_SourceProperties{} }
func (m *FirewallScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner_SourceProperties) ProtoMessage()    {}
func (*FirewallScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{1, 0}
}

func (m *FirewallScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Unmarshal(m, b)
}
func (m *FirewallScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *FirewallScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner_SourceProperties.Merge(m, src)
}
func (m *FirewallScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner_SourceProperties.Size(m)
}
func (m *FirewallScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner_SourceProperties proto.InternalMessageInfo

func (m *FirewallScanner_SourceProperties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetAllowed() string {
	if m != nil {
		return m.Allowed
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetAllowedIpRange() string {
	if m != nil {
		return m.AllowedIpRange
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetActivationTrigger() string {
	if m != nil {
		return m.ActivationTrigger
	}
	return ""
}

func (m *FirewallScanner_SourceProperties) GetSourceRange() string {
	if m != nil {
		return m.SourceRange
	}
	return ""
}

type FirewallScanner_Finding struct {
	SourceProperties     *FirewallScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                            `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                            `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FirewallScanner_Finding) Reset()         { *m = FirewallScanner_Finding{} }
func (m *FirewallScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*FirewallScanner_Finding) ProtoMessage()    {}
func (*FirewallScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{1, 1}
}

func (m *FirewallScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FirewallScanner_Finding.Unmarshal(m, b)
}
func (m *FirewallScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FirewallScanner_Finding.Marshal(b, m, deterministic)
}
func (m *FirewallScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirewallScanner_Finding.Merge(m, src)
}
func (m *FirewallScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_FirewallScanner_Finding.Size(m)
}
func (m *FirewallScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_FirewallScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_FirewallScanner_Finding proto.InternalMessageInfo

func (m *FirewallScanner_Finding) GetSourceProperties() *FirewallScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *FirewallScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *FirewallScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

type ComputeInstanceScanner struct {
	NotificationConfigName string                          `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *ComputeInstanceScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                        `json:"-"`
	XXX_unrecognized       []byte                          `json:"-"`
	XXX_sizecache          int32                           `json:"-"`
}

func (m *ComputeInstanceScanner) Reset()         { *m = ComputeInstanceScanner{} }
func (m *ComputeInstanceScanner) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner) ProtoMessage()    {}
func (*ComputeInstanceScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{2}
}

func (m *ComputeInstanceScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner.Merge(m, src)
}
func (m *ComputeInstanceScanner) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner.Size(m)
}
func (m *ComputeInstanceScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner proto.InternalMessageInfo

func (m *ComputeInstanceScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *ComputeInstanceScanner) GetFinding() *ComputeInstanceScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type ComputeInstanceScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ComputeInstanceScanner_SourceProperties) Reset() {
	*m = ComputeInstanceScanner_SourceProperties{}
}
func (m *ComputeInstanceScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner_SourceProperties) ProtoMessage()    {}
func (*ComputeInstanceScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{2, 0}
}

func (m *ComputeInstanceScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Merge(m, src)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner_SourceProperties.Size(m)
}
func (m *ComputeInstanceScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner_SourceProperties proto.InternalMessageInfo

func (m *ComputeInstanceScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type ComputeInstanceScanner_Finding struct {
	SourceProperties     *ComputeInstanceScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                                   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *ComputeInstanceScanner_Finding) Reset()         { *m = ComputeInstanceScanner_Finding{} }
func (m *ComputeInstanceScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*ComputeInstanceScanner_Finding) ProtoMessage()    {}
func (*ComputeInstanceScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{2, 1}
}

func (m *ComputeInstanceScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Unmarshal(m, b)
}
func (m *ComputeInstanceScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Marshal(b, m, deterministic)
}
func (m *ComputeInstanceScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComputeInstanceScanner_Finding.Merge(m, src)
}
func (m *ComputeInstanceScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_ComputeInstanceScanner_Finding.Size(m)
}
func (m *ComputeInstanceScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_ComputeInstanceScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_ComputeInstanceScanner_Finding proto.InternalMessageInfo

func (m *ComputeInstanceScanner_Finding) GetSourceProperties() *ComputeInstanceScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *ComputeInstanceScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type IamScanner struct {
	NotificationConfigName string              `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *IamScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}            `json:"-"`
	XXX_unrecognized       []byte              `json:"-"`
	XXX_sizecache          int32               `json:"-"`
}

func (m *IamScanner) Reset()         { *m = IamScanner{} }
func (m *IamScanner) String() string { return proto.CompactTextString(m) }
func (*IamScanner) ProtoMessage()    {}
func (*IamScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{3}
}

func (m *IamScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner.Unmarshal(m, b)
}
func (m *IamScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner.Marshal(b, m, deterministic)
}
func (m *IamScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner.Merge(m, src)
}
func (m *IamScanner) XXX_Size() int {
	return xxx_messageInfo_IamScanner.Size(m)
}
func (m *IamScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner proto.InternalMessageInfo

func (m *IamScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *IamScanner) GetFinding() *IamScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type IamScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	OffendingIamRoles    string   `protobuf:"bytes,2,opt,name=offendingIamRoles,proto3" json:"offendingIamRoles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IamScanner_SourceProperties) Reset()         { *m = IamScanner_SourceProperties{} }
func (m *IamScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*IamScanner_SourceProperties) ProtoMessage()    {}
func (*IamScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{3, 0}
}

func (m *IamScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner_SourceProperties.Unmarshal(m, b)
}
func (m *IamScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *IamScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner_SourceProperties.Merge(m, src)
}
func (m *IamScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_IamScanner_SourceProperties.Size(m)
}
func (m *IamScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner_SourceProperties proto.InternalMessageInfo

func (m *IamScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

func (m *IamScanner_SourceProperties) GetOffendingIamRoles() string {
	if m != nil {
		return m.OffendingIamRoles
	}
	return ""
}

type IamScanner_Finding struct {
	SourceProperties     *IamScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                       `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *IamScanner_Finding) Reset()         { *m = IamScanner_Finding{} }
func (m *IamScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*IamScanner_Finding) ProtoMessage()    {}
func (*IamScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{3, 1}
}

func (m *IamScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IamScanner_Finding.Unmarshal(m, b)
}
func (m *IamScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IamScanner_Finding.Marshal(b, m, deterministic)
}
func (m *IamScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IamScanner_Finding.Merge(m, src)
}
func (m *IamScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_IamScanner_Finding.Size(m)
}
func (m *IamScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_IamScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_IamScanner_Finding proto.InternalMessageInfo

func (m *IamScanner_Finding) GetSourceProperties() *IamScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *IamScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type SqlScanner struct {
	NotificationConfigName string              `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *SqlScanner_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}            `json:"-"`
	XXX_unrecognized       []byte              `json:"-"`
	XXX_sizecache          int32               `json:"-"`
}

func (m *SqlScanner) Reset()         { *m = SqlScanner{} }
func (m *SqlScanner) String() string { return proto.CompactTextString(m) }
func (*SqlScanner) ProtoMessage()    {}
func (*SqlScanner) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{4}
}

func (m *SqlScanner) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner.Unmarshal(m, b)
}
func (m *SqlScanner) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner.Marshal(b, m, deterministic)
}
func (m *SqlScanner) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner.Merge(m, src)
}
func (m *SqlScanner) XXX_Size() int {
	return xxx_messageInfo_SqlScanner.Size(m)
}
func (m *SqlScanner) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner proto.InternalMessageInfo

func (m *SqlScanner) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *SqlScanner) GetFinding() *SqlScanner_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type SqlScanner_SourceProperties struct {
	ProjectID            string   `protobuf:"bytes,1,opt,name=projectID,proto3" json:"projectID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SqlScanner_SourceProperties) Reset()         { *m = SqlScanner_SourceProperties{} }
func (m *SqlScanner_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*SqlScanner_SourceProperties) ProtoMessage()    {}
func (*SqlScanner_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{4, 0}
}

func (m *SqlScanner_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner_SourceProperties.Unmarshal(m, b)
}
func (m *SqlScanner_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner_SourceProperties.Marshal(b, m, deterministic)
}
func (m *SqlScanner_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner_SourceProperties.Merge(m, src)
}
func (m *SqlScanner_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_SqlScanner_SourceProperties.Size(m)
}
func (m *SqlScanner_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner_SourceProperties proto.InternalMessageInfo

func (m *SqlScanner_SourceProperties) GetProjectID() string {
	if m != nil {
		return m.ProjectID
	}
	return ""
}

type SqlScanner_Finding struct {
	SourceProperties     *SqlScanner_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                       `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                       `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *SqlScanner_Finding) Reset()         { *m = SqlScanner_Finding{} }
func (m *SqlScanner_Finding) String() string { return proto.CompactTextString(m) }
func (*SqlScanner_Finding) ProtoMessage()    {}
func (*SqlScanner_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_42ce1b275ac7c5c9, []int{4, 1}
}

func (m *SqlScanner_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SqlScanner_Finding.Unmarshal(m, b)
}
func (m *SqlScanner_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SqlScanner_Finding.Marshal(b, m, deterministic)
}
func (m *SqlScanner_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SqlScanner_Finding.Merge(m, src)
}
func (m *SqlScanner_Finding) XXX_Size() int {
	return xxx_messageInfo_SqlScanner_Finding.Size(m)
}
func (m *SqlScanner_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_SqlScanner_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_SqlScanner_Finding proto.InternalMessageInfo

func (m *SqlScanner_Finding) GetSourceProperties() *SqlScanner_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *SqlScanner_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *SqlScanner_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func init() {
	proto.RegisterType((*StorageScanner)(nil), "StorageScanner")
	proto.RegisterType((*StorageScanner_SourceProperties)(nil), "StorageScanner.SourceProperties")
	proto.RegisterType((*StorageScanner_Finding)(nil), "StorageScanner.Finding")
	proto.RegisterType((*FirewallScanner)(nil), "FirewallScanner")
	proto.RegisterType((*FirewallScanner_SourceProperties)(nil), "FirewallScanner.SourceProperties")
	proto.RegisterType((*FirewallScanner_Finding)(nil), "FirewallScanner.Finding")
	proto.RegisterType((*ComputeInstanceScanner)(nil), "ComputeInstanceScanner")
	proto.RegisterType((*ComputeInstanceScanner_SourceProperties)(nil), "ComputeInstanceScanner.SourceProperties")
	proto.RegisterType((*ComputeInstanceScanner_Finding)(nil), "ComputeInstanceScanner.Finding")
	proto.RegisterType((*IamScanner)(nil), "IamScanner")
	proto.RegisterType((*IamScanner_SourceProperties)(nil), "IamScanner.SourceProperties")
	proto.RegisterType((*IamScanner_Finding)(nil), "IamScanner.Finding")
	proto.RegisterType((*SqlScanner)(nil), "SqlScanner")
	proto.RegisterType((*SqlScanner_SourceProperties)(nil), "SqlScanner.SourceProperties")
	proto.RegisterType((*SqlScanner_Finding)(nil), "SqlScanner.Finding")
}

func init() { proto.RegisterFile("sha/protos/sha.proto", fileDescriptor_42ce1b275ac7c5c9) }

var fileDescriptor_42ce1b275ac7c5c9 = []byte{
	// 475 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0x49, 0x56, 0x5d, 0xfb, 0x56, 0x6a, 0x1d, 0xa5, 0x86, 0x50, 0x70, 0xcd, 0x41, 0xf6,
	0xa0, 0xa9, 0xae, 0x20, 0x78, 0x6e, 0x29, 0x06, 0x54, 0x24, 0xdb, 0xb3, 0x30, 0x66, 0x5f, 0xd2,
	0x91, 0x64, 0x26, 0x4e, 0xa6, 0x16, 0xf1, 0x63, 0x78, 0xd0, 0xcf, 0xa2, 0x37, 0x11, 0xfc, 0x14,
	0x7e, 0x17, 0x71, 0x92, 0x9a, 0xec, 0x8c, 0x81, 0x2e, 0x71, 0x6f, 0x99, 0xf7, 0xe6, 0xbd, 0xff,
	0xbc, 0xdf, 0x7f, 0x86, 0xc0, 0xad, 0xea, 0x84, 0xee, 0x97, 0x52, 0x28, 0x51, 0xed, 0x57, 0x27,
	0x34, 0xd4, 0x9f, 0xc1, 0x4f, 0x17, 0xb6, 0x17, 0x4a, 0x48, 0x9a, 0xe1, 0x22, 0xa1, 0x9c, 0xa3,
	0x24, 0x4f, 0x60, 0x97, 0x0b, 0xc5, 0x52, 0x96, 0x50, 0xc5, 0x04, 0x3f, 0x10, 0x3c, 0x65, 0xd9,
	0x4b, 0x5a, 0xa0, 0xe7, 0x4c, 0x9d, 0xd9, 0x56, 0xdc, 0x93, 0x25, 0x8f, 0x60, 0x9c, 0x32, 0xbe,
	0x64, 0x3c, 0xf3, 0xdc, 0xa9, 0x33, 0x9b, 0xcc, 0x6f, 0x87, 0xab, 0x9d, 0xc3, 0xa3, 0x3a, 0x1d,
	0x9f, 0xef, 0xf3, 0x1f, 0xc2, 0xce, 0x42, 0x9c, 0xca, 0x04, 0x5f, 0x49, 0x51, 0xa2, 0x54, 0x0c,
	0x2b, 0xb2, 0x07, 0x5b, 0xa5, 0x14, 0x6f, 0x31, 0x51, 0xd1, 0xb2, 0x51, 0x6c, 0x03, 0xfe, 0x67,
	0x07, 0xc6, 0x4d, 0x1b, 0xf2, 0x1c, 0x76, 0x2a, 0xa3, 0x5a, 0x17, 0x4c, 0xe6, 0x53, 0x53, 0xd9,
	0x54, 0x89, 0xad, 0x4a, 0x12, 0xc0, 0x35, 0x89, 0x75, 0x54, 0x0f, 0xeb, 0x6a, 0xe9, 0x95, 0x18,
	0xf1, 0xe1, 0x6a, 0x42, 0x15, 0x66, 0x42, 0x7e, 0xf0, 0x46, 0x3a, 0xff, 0x77, 0x1d, 0xfc, 0x1a,
	0xc1, 0xf5, 0x23, 0x26, 0xf1, 0x8c, 0xe6, 0xf9, 0x50, 0x94, 0x73, 0x13, 0xa5, 0x17, 0x1a, 0xad,
	0x6d, 0x96, 0xdf, 0x9d, 0x75, 0x61, 0x12, 0x0f, 0xc6, 0x34, 0xcf, 0xc5, 0x19, 0x2e, 0x9b, 0x69,
	0xcf, 0x97, 0xe4, 0x1e, 0x6c, 0x37, 0x9f, 0x51, 0x19, 0x53, 0x9e, 0x61, 0x33, 0xae, 0x11, 0x25,
	0xf7, 0xe1, 0x06, 0x4d, 0x14, 0x7b, 0xaf, 0x07, 0x38, 0x96, 0x2c, 0xcb, 0x50, 0x7a, 0x97, 0xf4,
	0x56, 0x3b, 0x41, 0xa6, 0x30, 0xa9, 0x61, 0xd6, 0x2d, 0x2f, 0xeb, 0x7d, 0xdd, 0x90, 0xff, 0xa5,
	0x63, 0xef, 0x8b, 0x5e, 0x7b, 0xef, 0x5a, 0x34, 0x2e, 0xe0, 0x6f, 0xd7, 0x3b, 0x77, 0xd5, 0x3b,
	0xcb, 0xfb, 0x91, 0xed, 0x7d, 0xf0, 0xd5, 0x85, 0xdd, 0x03, 0x51, 0x94, 0xa7, 0x0a, 0x23, 0x5e,
	0x29, 0xca, 0x93, 0xc1, 0x2f, 0xe6, 0xa9, 0x69, 0xf3, 0x9d, 0xf0, 0xdf, 0x0a, 0x6b, 0xbf, 0x9c,
	0x43, 0xd3, 0xec, 0x43, 0xff, 0x63, 0x4b, 0xf6, 0xb8, 0x97, 0xec, 0xac, 0xef, 0x00, 0xc3, 0x00,
	0x07, 0x3f, 0x5c, 0x80, 0x88, 0x16, 0x43, 0x81, 0x3d, 0x30, 0x81, 0xdd, 0x0c, 0xdb, 0xae, 0x36,
	0xa4, 0xd7, 0xeb, 0x42, 0xfa, 0x73, 0x9f, 0x45, 0x9a, 0xa2, 0x2e, 0x8f, 0x68, 0x11, 0x8b, 0x1c,
	0xab, 0x66, 0x18, 0x3b, 0xe1, 0x8b, 0x16, 0xe9, 0xb3, 0x5e, 0xa4, 0x7b, 0xdd, 0x23, 0x0e, 0xc4,
	0xf8, 0xcd, 0x05, 0x58, 0xbc, 0xcb, 0x37, 0x80, 0xb1, 0xed, 0xfa, 0x3f, 0xee, 0xda, 0x27, 0xe7,
	0x62, 0x64, 0x3a, 0xaa, 0x9b, 0x7f, 0xc1, 0x6f, 0xae, 0xe8, 0x5f, 0xde, 0xe3, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x9c, 0xde, 0x2b, 0x04, 0x0a, 0x07, 0x00, 0x00,
}
