#!/bin/bash
# - Script does not stop on failures so final step (removal of pubsub.admin) completes if a prior
#   failure happens.
SERVICE_ACCOUNT_EMAIL=automation-service-account@aerial-jigsaw-235219.iam.gserviceaccount.com \
  ORGANIZATION_ID=154584661726 \
  PROJECT_ID=aerial-jigsaw-235219 \
  TOPIC_ID=cscc-notifications-topic

echo "Temporarily granting pubsub.admin to service account."
gcloud organizations add-iam-policy-binding $ORGANIZATION_ID \
  --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
  --role='roles/pubsub.admin'

echo "Create notification config."
go run ./local/cli/main.go \
  --command create \
  --org-id=$ORGANIZATION_ID \
  --topic=projects/aerial-jigsaw-235219/topics/cscc-notifications-topic

echo "Get service account generated by CLI and grant it Pub/Sub publisher."
gcloud beta pubsub topics add-iam-policy-binding projects/$PROJECT_ID/topics/$TOPIC_ID \
  --member="serviceAccount:service-997507777601@gcp-sa-scc-notification.iam.gserviceaccount.com" \
  --role="roles/pubsub.publisher"

echo "Remove Pub/Sub admin."
gcloud organizations remove-iam-policy-binding $ORGANIZATION_ID \
  --member="serviceAccount:$SERVICE_ACCOUNT_EMAIL" \
  --role='roles/pubsub.admin'
