apiVersion: security-response-automation.cloud.google.com/v1alpha1
kind: RemediationFunction
metadata:
  name: gce_create_disk_snapshot
spec:
  match:
    target:
      - organization/*
    exclude:
      - folder/123
      - project/456
  validation:
    openAPIV3Schema:
      properties:
        dry_run: true
        target_snapshot_project_id: foo-123
        target_snapshot_zone: us-central1
        output:
          - turbinia
        turbinia:
          project_id: foo-123
          topic: bar-234
          zone: us-central1
