// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stackdriver/protos/stackdriver.proto

package stackdriver

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Finish.
type BadDomain struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadDomain) Reset()         { *m = BadDomain{} }
func (m *BadDomain) String() string { return proto.CompactTextString(m) }
func (*BadDomain) ProtoMessage()    {}
func (*BadDomain) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{0}
}

func (m *BadDomain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadDomain.Unmarshal(m, b)
}
func (m *BadDomain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadDomain.Marshal(b, m, deterministic)
}
func (m *BadDomain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadDomain.Merge(m, src)
}
func (m *BadDomain) XXX_Size() int {
	return xxx_messageInfo_BadDomain.Size(m)
}
func (m *BadDomain) XXX_DiscardUnknown() {
	xxx_messageInfo_BadDomain.DiscardUnknown(m)
}

var xxx_messageInfo_BadDomain proto.InternalMessageInfo

func (m *BadDomain) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type AnomalousIAMGrant struct {
	InsertId             string                         `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                         `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *AnomalousIAMGrant_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AnomalousIAMGrant) Reset()         { *m = AnomalousIAMGrant{} }
func (m *AnomalousIAMGrant) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant) ProtoMessage()    {}
func (*AnomalousIAMGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{1}
}

func (m *AnomalousIAMGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant.Merge(m, src)
}
func (m *AnomalousIAMGrant) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant.Size(m)
}
func (m *AnomalousIAMGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant proto.InternalMessageInfo

func (m *AnomalousIAMGrant) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *AnomalousIAMGrant) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *AnomalousIAMGrant) GetJsonPayload() *AnomalousIAMGrant_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type AnomalousIAMGrant_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExternalMembers      []string `protobuf:"bytes,2,rep,name=externalMembers,proto3" json:"externalMembers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_Properties) Reset()         { *m = AnomalousIAMGrant_Properties{} }
func (m *AnomalousIAMGrant_Properties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_Properties) ProtoMessage()    {}
func (*AnomalousIAMGrant_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{1, 0}
}

func (m *AnomalousIAMGrant_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_Properties.Merge(m, src)
}
func (m *AnomalousIAMGrant_Properties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Size(m)
}
func (m *AnomalousIAMGrant_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_Properties proto.InternalMessageInfo

func (m *AnomalousIAMGrant_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AnomalousIAMGrant_Properties) GetExternalMembers() []string {
	if m != nil {
		return m.ExternalMembers
	}
	return nil
}

type AnomalousIAMGrant_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_AffectedResource) Reset()         { *m = AnomalousIAMGrant_AffectedResource{} }
func (m *AnomalousIAMGrant_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_AffectedResource) ProtoMessage()    {}
func (*AnomalousIAMGrant_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{1, 1}
}

func (m *AnomalousIAMGrant_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Merge(m, src)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Size(m)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_AffectedResource proto.InternalMessageInfo

func (m *AnomalousIAMGrant_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type AnomalousIAMGrant_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	SubRuleName          string   `protobuf:"bytes,2,opt,name=subRuleName,proto3" json:"subRuleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_DetectionCategory) Reset()         { *m = AnomalousIAMGrant_DetectionCategory{} }
func (m *AnomalousIAMGrant_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_DetectionCategory) ProtoMessage()    {}
func (*AnomalousIAMGrant_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{1, 2}
}

func (m *AnomalousIAMGrant_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Merge(m, src)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Size(m)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_DetectionCategory proto.InternalMessageInfo

func (m *AnomalousIAMGrant_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *AnomalousIAMGrant_DetectionCategory) GetSubRuleName() string {
	if m != nil {
		return m.SubRuleName
	}
	return ""
}

type AnomalousIAMGrant_JSONPayload struct {
	AffectedResources    []*AnomalousIAMGrant_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *AnomalousIAMGrant_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *AnomalousIAMGrant_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *AnomalousIAMGrant_JSONPayload) Reset()         { *m = AnomalousIAMGrant_JSONPayload{} }
func (m *AnomalousIAMGrant_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_JSONPayload) ProtoMessage()    {}
func (*AnomalousIAMGrant_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{1, 3}
}

func (m *AnomalousIAMGrant_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Merge(m, src)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Size(m)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_JSONPayload proto.InternalMessageInfo

func (m *AnomalousIAMGrant_JSONPayload) GetAffectedResources() []*AnomalousIAMGrant_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetProperties() *AnomalousIAMGrant_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetDetectionCategory() *AnomalousIAMGrant_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIP struct {
	InsertId             string             `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string             `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *BadIP_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BadIP) Reset()         { *m = BadIP{} }
func (m *BadIP) String() string { return proto.CompactTextString(m) }
func (*BadIP) ProtoMessage()    {}
func (*BadIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{2}
}

func (m *BadIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP.Unmarshal(m, b)
}
func (m *BadIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP.Marshal(b, m, deterministic)
}
func (m *BadIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP.Merge(m, src)
}
func (m *BadIP) XXX_Size() int {
	return xxx_messageInfo_BadIP.Size(m)
}
func (m *BadIP) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP proto.InternalMessageInfo

func (m *BadIP) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *BadIP) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *BadIP) GetJsonPayload() *BadIP_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type BadIP_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	InstanceDetails      string   `protobuf:"bytes,3,opt,name=instanceDetails,proto3" json:"instanceDetails,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_Properties) Reset()         { *m = BadIP_Properties{} }
func (m *BadIP_Properties) String() string { return proto.CompactTextString(m) }
func (*BadIP_Properties) ProtoMessage()    {}
func (*BadIP_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{2, 0}
}

func (m *BadIP_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_Properties.Unmarshal(m, b)
}
func (m *BadIP_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_Properties.Marshal(b, m, deterministic)
}
func (m *BadIP_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_Properties.Merge(m, src)
}
func (m *BadIP_Properties) XXX_Size() int {
	return xxx_messageInfo_BadIP_Properties.Size(m)
}
func (m *BadIP_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_Properties proto.InternalMessageInfo

func (m *BadIP_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *BadIP_Properties) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *BadIP_Properties) GetInstanceDetails() string {
	if m != nil {
		return m.InstanceDetails
	}
	return ""
}

func (m *BadIP_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type BadIP_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_AffectedResource) Reset()         { *m = BadIP_AffectedResource{} }
func (m *BadIP_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*BadIP_AffectedResource) ProtoMessage()    {}
func (*BadIP_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{2, 1}
}

func (m *BadIP_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_AffectedResource.Unmarshal(m, b)
}
func (m *BadIP_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_AffectedResource.Marshal(b, m, deterministic)
}
func (m *BadIP_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_AffectedResource.Merge(m, src)
}
func (m *BadIP_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_BadIP_AffectedResource.Size(m)
}
func (m *BadIP_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_AffectedResource proto.InternalMessageInfo

func (m *BadIP_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type BadIP_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_DetectionCategory) Reset()         { *m = BadIP_DetectionCategory{} }
func (m *BadIP_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*BadIP_DetectionCategory) ProtoMessage()    {}
func (*BadIP_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{2, 2}
}

func (m *BadIP_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_DetectionCategory.Unmarshal(m, b)
}
func (m *BadIP_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *BadIP_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_DetectionCategory.Merge(m, src)
}
func (m *BadIP_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_BadIP_DetectionCategory.Size(m)
}
func (m *BadIP_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_DetectionCategory proto.InternalMessageInfo

func (m *BadIP_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type BadIP_JSONPayload struct {
	AffectedResources    []*BadIP_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *BadIP_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *BadIP_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BadIP_JSONPayload) Reset()         { *m = BadIP_JSONPayload{} }
func (m *BadIP_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*BadIP_JSONPayload) ProtoMessage()    {}
func (*BadIP_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{2, 3}
}

func (m *BadIP_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_JSONPayload.Unmarshal(m, b)
}
func (m *BadIP_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_JSONPayload.Marshal(b, m, deterministic)
}
func (m *BadIP_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_JSONPayload.Merge(m, src)
}
func (m *BadIP_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_BadIP_JSONPayload.Size(m)
}
func (m *BadIP_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_JSONPayload proto.InternalMessageInfo

func (m *BadIP_JSONPayload) GetAffectedResources() []*BadIP_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *BadIP_JSONPayload) GetProperties() *BadIP_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BadIP_JSONPayload) GetDetectionCategory() *BadIP_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type SshBruteForce struct {
	InsertId             string                     `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                     `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *SshBruteForce_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SshBruteForce) Reset()         { *m = SshBruteForce{} }
func (m *SshBruteForce) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce) ProtoMessage()    {}
func (*SshBruteForce) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3}
}

func (m *SshBruteForce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce.Unmarshal(m, b)
}
func (m *SshBruteForce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce.Marshal(b, m, deterministic)
}
func (m *SshBruteForce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce.Merge(m, src)
}
func (m *SshBruteForce) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce.Size(m)
}
func (m *SshBruteForce) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce proto.InternalMessageInfo

func (m *SshBruteForce) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *SshBruteForce) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *SshBruteForce) GetJsonPayload() *SshBruteForce_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type SshBruteForce_LoginAttempt struct {
	AuthResult           string   `protobuf:"bytes,1,opt,name=authResult,proto3" json:"authResult,omitempty"`
	SourceIp             string   `protobuf:"bytes,2,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	VmName               string   `protobuf:"bytes,4,opt,name=vmName,proto3" json:"vmName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_LoginAttempt) Reset()         { *m = SshBruteForce_LoginAttempt{} }
func (m *SshBruteForce_LoginAttempt) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_LoginAttempt) ProtoMessage()    {}
func (*SshBruteForce_LoginAttempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3, 0}
}

func (m *SshBruteForce_LoginAttempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Unmarshal(m, b)
}
func (m *SshBruteForce_LoginAttempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_LoginAttempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_LoginAttempt.Merge(m, src)
}
func (m *SshBruteForce_LoginAttempt) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Size(m)
}
func (m *SshBruteForce_LoginAttempt) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_LoginAttempt.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_LoginAttempt proto.InternalMessageInfo

func (m *SshBruteForce_LoginAttempt) GetAuthResult() string {
	if m != nil {
		return m.AuthResult
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetVmName() string {
	if m != nil {
		return m.VmName
	}
	return ""
}

type SshBruteForce_Properties struct {
	InstanceId           string                        `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProjectId            string                        `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Zone                 string                        `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	LoginAttempts        []*SshBruteForce_LoginAttempt `protobuf:"bytes,4,rep,name=LoginAttempts,json=loginAttempts,proto3" json:"LoginAttempts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SshBruteForce_Properties) Reset()         { *m = SshBruteForce_Properties{} }
func (m *SshBruteForce_Properties) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_Properties) ProtoMessage()    {}
func (*SshBruteForce_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3, 1}
}

func (m *SshBruteForce_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_Properties.Unmarshal(m, b)
}
func (m *SshBruteForce_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_Properties.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_Properties.Merge(m, src)
}
func (m *SshBruteForce_Properties) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_Properties.Size(m)
}
func (m *SshBruteForce_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_Properties proto.InternalMessageInfo

func (m *SshBruteForce_Properties) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *SshBruteForce_Properties) GetLoginAttempts() []*SshBruteForce_LoginAttempt {
	if m != nil {
		return m.LoginAttempts
	}
	return nil
}

type SshBruteForce_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_AffectedResource) Reset()         { *m = SshBruteForce_AffectedResource{} }
func (m *SshBruteForce_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_AffectedResource) ProtoMessage()    {}
func (*SshBruteForce_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3, 2}
}

func (m *SshBruteForce_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Unmarshal(m, b)
}
func (m *SshBruteForce_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_AffectedResource.Merge(m, src)
}
func (m *SshBruteForce_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Size(m)
}
func (m *SshBruteForce_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_AffectedResource proto.InternalMessageInfo

func (m *SshBruteForce_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type SshBruteForce_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_DetectionCategory) Reset()         { *m = SshBruteForce_DetectionCategory{} }
func (m *SshBruteForce_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_DetectionCategory) ProtoMessage()    {}
func (*SshBruteForce_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3, 3}
}

func (m *SshBruteForce_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Unmarshal(m, b)
}
func (m *SshBruteForce_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_DetectionCategory.Merge(m, src)
}
func (m *SshBruteForce_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Size(m)
}
func (m *SshBruteForce_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_DetectionCategory proto.InternalMessageInfo

func (m *SshBruteForce_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type SshBruteForce_JSONPayload struct {
	AffectedResources    []*SshBruteForce_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *SshBruteForce_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *SshBruteForce_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SshBruteForce_JSONPayload) Reset()         { *m = SshBruteForce_JSONPayload{} }
func (m *SshBruteForce_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_JSONPayload) ProtoMessage()    {}
func (*SshBruteForce_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_8a2e507346a389c4, []int{3, 4}
}

func (m *SshBruteForce_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Unmarshal(m, b)
}
func (m *SshBruteForce_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_JSONPayload.Merge(m, src)
}
func (m *SshBruteForce_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Size(m)
}
func (m *SshBruteForce_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_JSONPayload proto.InternalMessageInfo

func (m *SshBruteForce_JSONPayload) GetAffectedResources() []*SshBruteForce_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetProperties() *SshBruteForce_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetDetectionCategory() *SshBruteForce_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

func init() {
	proto.RegisterType((*BadDomain)(nil), "BadDomain")
	proto.RegisterType((*AnomalousIAMGrant)(nil), "AnomalousIAMGrant")
	proto.RegisterType((*AnomalousIAMGrant_Properties)(nil), "AnomalousIAMGrant.Properties")
	proto.RegisterType((*AnomalousIAMGrant_AffectedResource)(nil), "AnomalousIAMGrant.AffectedResource")
	proto.RegisterType((*AnomalousIAMGrant_DetectionCategory)(nil), "AnomalousIAMGrant.DetectionCategory")
	proto.RegisterType((*AnomalousIAMGrant_JSONPayload)(nil), "AnomalousIAMGrant.JSONPayload")
	proto.RegisterType((*BadIP)(nil), "BadIP")
	proto.RegisterType((*BadIP_Properties)(nil), "BadIP.Properties")
	proto.RegisterType((*BadIP_AffectedResource)(nil), "BadIP.AffectedResource")
	proto.RegisterType((*BadIP_DetectionCategory)(nil), "BadIP.DetectionCategory")
	proto.RegisterType((*BadIP_JSONPayload)(nil), "BadIP.JSONPayload")
	proto.RegisterType((*SshBruteForce)(nil), "SshBruteForce")
	proto.RegisterType((*SshBruteForce_LoginAttempt)(nil), "SshBruteForce.LoginAttempt")
	proto.RegisterType((*SshBruteForce_Properties)(nil), "SshBruteForce.Properties")
	proto.RegisterType((*SshBruteForce_AffectedResource)(nil), "SshBruteForce.AffectedResource")
	proto.RegisterType((*SshBruteForce_DetectionCategory)(nil), "SshBruteForce.DetectionCategory")
	proto.RegisterType((*SshBruteForce_JSONPayload)(nil), "SshBruteForce.JSONPayload")
}

func init() {
	proto.RegisterFile("stackdriver/protos/stackdriver.proto", fileDescriptor_8a2e507346a389c4)
}

var fileDescriptor_8a2e507346a389c4 = []byte{
	// 648 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x95, 0xc1, 0x4e, 0xd4, 0x5e,
	0x14, 0xc6, 0x33, 0xcc, 0xfc, 0xf9, 0x33, 0xa7, 0x12, 0x9d, 0xbb, 0xd0, 0x5a, 0x03, 0x4c, 0x90,
	0xc5, 0xc4, 0xc5, 0x10, 0xd1, 0x8d, 0x09, 0x26, 0x0e, 0x22, 0xa6, 0x46, 0x10, 0x2e, 0x71, 0x4d,
	0x2e, 0xed, 0x61, 0x28, 0xb6, 0xbd, 0xcd, 0xbd, 0xb7, 0x44, 0x5c, 0xb8, 0x30, 0xf1, 0x49, 0x7c,
	0x0d, 0xdf, 0xc1, 0xc7, 0x30, 0xae, 0x7d, 0x01, 0xd3, 0xdb, 0x76, 0x28, 0x77, 0xda, 0x64, 0xc0,
	0xc4, 0x1d, 0xe7, 0x3b, 0xfd, 0x4e, 0xcf, 0xf9, 0xfa, 0x23, 0x03, 0x6b, 0x52, 0x31, 0xef, 0x83,
	0x2f, 0x82, 0x73, 0x14, 0xeb, 0x89, 0xe0, 0x8a, 0xcb, 0xf5, 0x8a, 0x34, 0xd4, 0xd2, 0xea, 0x23,
	0xe8, 0x6e, 0x31, 0x7f, 0x9b, 0x47, 0x2c, 0x88, 0xc9, 0x12, 0x40, 0x90, 0x1c, 0x31, 0xdf, 0x17,
	0x28, 0xa5, 0xdd, 0xea, 0xb7, 0x06, 0x5d, 0xda, 0x0d, 0x92, 0x51, 0x2e, 0xac, 0xfe, 0xea, 0x40,
	0x6f, 0x14, 0xf3, 0x88, 0x85, 0x3c, 0x95, 0xee, 0x68, 0xf7, 0xb5, 0x60, 0xb1, 0x22, 0x0e, 0x2c,
	0x04, 0xb1, 0x44, 0xa1, 0x5c, 0xbf, 0xb0, 0x4c, 0x6a, 0x62, 0xc3, 0xff, 0x21, 0x1f, 0xef, 0xb1,
	0x08, 0xed, 0x39, 0xdd, 0x2a, 0x4b, 0xf2, 0x02, 0xac, 0x33, 0xc9, 0xe3, 0x7d, 0x76, 0x11, 0x72,
	0xe6, 0xdb, 0xed, 0x7e, 0x6b, 0x60, 0x6d, 0x2c, 0x0f, 0xa7, 0xc6, 0x0f, 0xdf, 0x1c, 0xbe, 0xdb,
	0x2b, 0x9e, 0xa2, 0x55, 0x8b, 0xf3, 0x1e, 0x60, 0x5f, 0xf0, 0x04, 0x85, 0x0a, 0x50, 0x66, 0xab,
	0x27, 0x82, 0x9f, 0xa1, 0xa7, 0x8e, 0x82, 0x72, 0x8f, 0x6e, 0xa1, 0xb8, 0x3e, 0x19, 0xc0, 0x6d,
	0xfc, 0xa8, 0x50, 0xc4, 0x2c, 0xdc, 0xc5, 0xe8, 0x18, 0x85, 0xb4, 0xe7, 0xfa, 0xed, 0x41, 0x97,
	0x9a, 0xb2, 0xb3, 0x09, 0x77, 0x46, 0x27, 0x27, 0xe8, 0x29, 0xf4, 0x29, 0x4a, 0x9e, 0x0a, 0x0f,
	0x33, 0xf7, 0xd8, 0x4b, 0xca, 0x52, 0x9f, 0x93, 0xbf, 0xc1, 0x94, 0x9d, 0x03, 0xe8, 0x6d, 0xa3,
	0x42, 0x4f, 0x05, 0x3c, 0x7e, 0xc9, 0x14, 0x8e, 0xb9, 0xb8, 0xc8, 0x12, 0x12, 0x69, 0x58, 0xf5,
	0x4d, 0x6a, 0xd2, 0x07, 0x4b, 0xa6, 0xc7, 0xb4, 0x6c, 0xe7, 0x29, 0x55, 0x25, 0xe7, 0x77, 0x0b,
	0xac, 0x4a, 0x08, 0xe4, 0x00, 0x7a, 0xcc, 0x58, 0x30, 0xfb, 0x56, 0xed, 0x81, 0xb5, 0xf1, 0xb0,
	0x26, 0x3f, 0xf3, 0x18, 0x3a, 0xed, 0x26, 0xcf, 0x75, 0x78, 0x45, 0x94, 0x7a, 0x07, 0x6b, 0x63,
	0xa9, 0x66, 0xd6, 0x65, 0xde, 0xb4, 0x62, 0x20, 0x14, 0x7a, 0xbe, 0x79, 0x74, 0xf1, 0x45, 0xd7,
	0x6a, 0xa6, 0x4c, 0x05, 0x44, 0xa7, 0xed, 0xab, 0xdf, 0x3b, 0xf0, 0xdf, 0x16, 0xf3, 0xdd, 0xfd,
	0x1b, 0xf2, 0xf5, 0xb4, 0x8e, 0x2f, 0x32, 0xd4, 0x23, 0x9b, 0x99, 0xfa, 0xda, 0xba, 0x0e, 0x54,
	0x0e, 0x2c, 0x84, 0xdc, 0x63, 0xd9, 0xde, 0xc5, 0xeb, 0x27, 0x75, 0x86, 0x4c, 0x10, 0x4b, 0xc5,
	0x62, 0x0f, 0xb7, 0x51, 0xb1, 0x20, 0x94, 0x7a, 0x87, 0x2e, 0x35, 0x65, 0x42, 0xa0, 0xf3, 0x89,
	0xc7, 0x68, 0x77, 0x74, 0x5b, 0xff, 0xfd, 0x97, 0x10, 0xae, 0x5f, 0x13, 0x42, 0xe7, 0x87, 0x81,
	0xd8, 0xab, 0x66, 0xc4, 0xee, 0x15, 0x11, 0xce, 0x82, 0xd5, 0xe3, 0x1a, 0xac, 0x7a, 0x85, 0xbf,
	0x01, 0xa5, 0x9d, 0x66, 0x94, 0xec, 0xc2, 0x39, 0x13, 0x3e, 0x5f, 0xe6, 0x61, 0xf1, 0x50, 0x9e,
	0x6e, 0x89, 0x54, 0xe1, 0x0e, 0xcf, 0xe2, 0xbb, 0x19, 0x46, 0x9b, 0x75, 0x18, 0x39, 0xc3, 0x2b,
	0xa3, 0x9b, 0x71, 0xfa, 0x0c, 0xb7, 0xde, 0xf2, 0x71, 0x10, 0x8f, 0x94, 0xc2, 0x28, 0x51, 0x64,
	0x19, 0x80, 0xa5, 0xea, 0x94, 0xa2, 0x4c, 0x43, 0x55, 0x6c, 0x51, 0x51, 0xb2, 0x1d, 0xf3, 0xec,
	0xdc, 0xa4, 0x04, 0xaa, 0xac, 0xb3, 0x5e, 0x2a, 0x51, 0xe8, 0x25, 0x73, 0x92, 0x26, 0x35, 0xb9,
	0x0b, 0xf3, 0xe7, 0x91, 0xee, 0xe4, 0x10, 0x15, 0x95, 0xf3, 0xed, 0x2a, 0xce, 0x2b, 0x60, 0x95,
	0xf0, 0x5d, 0xf2, 0x0c, 0xa5, 0xe4, 0xfa, 0x06, 0xef, 0x73, 0x26, 0xef, 0x25, 0xa9, 0xed, 0x4b,
	0x52, 0xc9, 0x08, 0x16, 0xab, 0x27, 0x4a, 0xbb, 0xa3, 0x31, 0x79, 0x60, 0x44, 0x54, 0x7d, 0x86,
	0x2e, 0x86, 0x55, 0xc7, 0xbf, 0x86, 0xfd, 0xa7, 0x01, 0xfb, 0x6e, 0x33, 0xec, 0x2b, 0xc6, 0x15,
	0xb3, 0x40, 0xff, 0xac, 0x06, 0xfa, 0xfb, 0xc6, 0x9c, 0x06, 0xf8, 0xf7, 0x9a, 0xe1, 0xef, 0x1b,
	0x13, 0x66, 0xf9, 0x27, 0x38, 0x9e, 0xd7, 0x3f, 0xf1, 0x4f, 0xfe, 0x04, 0x00, 0x00, 0xff, 0xff,
	0x34, 0xda, 0xaa, 0x86, 0x0a, 0x08, 0x00, 0x00,
}
