// Code generated by protoc-gen-go. DO NOT EDIT.
// source: etd/protos/etd.proto

package etd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Finish.
type BadDomain struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadDomain) Reset()         { *m = BadDomain{} }
func (m *BadDomain) String() string { return proto.CompactTextString(m) }
func (*BadDomain) ProtoMessage()    {}
func (*BadDomain) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{0}
}

func (m *BadDomain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadDomain.Unmarshal(m, b)
}
func (m *BadDomain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadDomain.Marshal(b, m, deterministic)
}
func (m *BadDomain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadDomain.Merge(m, src)
}
func (m *BadDomain) XXX_Size() int {
	return xxx_messageInfo_BadDomain.Size(m)
}
func (m *BadDomain) XXX_DiscardUnknown() {
	xxx_messageInfo_BadDomain.DiscardUnknown(m)
}

var xxx_messageInfo_BadDomain proto.InternalMessageInfo

func (m *BadDomain) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type AnomalousIAMGrant struct {
	InsertId             string                         `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                         `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *AnomalousIAMGrant_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AnomalousIAMGrant) Reset()         { *m = AnomalousIAMGrant{} }
func (m *AnomalousIAMGrant) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant) ProtoMessage()    {}
func (*AnomalousIAMGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1}
}

func (m *AnomalousIAMGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant.Merge(m, src)
}
func (m *AnomalousIAMGrant) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant.Size(m)
}
func (m *AnomalousIAMGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant proto.InternalMessageInfo

func (m *AnomalousIAMGrant) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *AnomalousIAMGrant) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *AnomalousIAMGrant) GetJsonPayload() *AnomalousIAMGrant_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type AnomalousIAMGrant_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExternalMembers      []string `protobuf:"bytes,2,rep,name=externalMembers,proto3" json:"externalMembers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_Properties) Reset()         { *m = AnomalousIAMGrant_Properties{} }
func (m *AnomalousIAMGrant_Properties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_Properties) ProtoMessage()    {}
func (*AnomalousIAMGrant_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 0}
}

func (m *AnomalousIAMGrant_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_Properties.Merge(m, src)
}
func (m *AnomalousIAMGrant_Properties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Size(m)
}
func (m *AnomalousIAMGrant_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_Properties proto.InternalMessageInfo

func (m *AnomalousIAMGrant_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AnomalousIAMGrant_Properties) GetExternalMembers() []string {
	if m != nil {
		return m.ExternalMembers
	}
	return nil
}

type AnomalousIAMGrant_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_AffectedResource) Reset()         { *m = AnomalousIAMGrant_AffectedResource{} }
func (m *AnomalousIAMGrant_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_AffectedResource) ProtoMessage()    {}
func (*AnomalousIAMGrant_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 1}
}

func (m *AnomalousIAMGrant_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Merge(m, src)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Size(m)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_AffectedResource proto.InternalMessageInfo

func (m *AnomalousIAMGrant_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type AnomalousIAMGrant_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	SubRuleName          string   `protobuf:"bytes,2,opt,name=subRuleName,proto3" json:"subRuleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_DetectionCategory) Reset()         { *m = AnomalousIAMGrant_DetectionCategory{} }
func (m *AnomalousIAMGrant_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_DetectionCategory) ProtoMessage()    {}
func (*AnomalousIAMGrant_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 2}
}

func (m *AnomalousIAMGrant_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Merge(m, src)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Size(m)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_DetectionCategory proto.InternalMessageInfo

func (m *AnomalousIAMGrant_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *AnomalousIAMGrant_DetectionCategory) GetSubRuleName() string {
	if m != nil {
		return m.SubRuleName
	}
	return ""
}

type AnomalousIAMGrant_JSONPayload struct {
	AffectedResources    []*AnomalousIAMGrant_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *AnomalousIAMGrant_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *AnomalousIAMGrant_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *AnomalousIAMGrant_JSONPayload) Reset()         { *m = AnomalousIAMGrant_JSONPayload{} }
func (m *AnomalousIAMGrant_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_JSONPayload) ProtoMessage()    {}
func (*AnomalousIAMGrant_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 3}
}

func (m *AnomalousIAMGrant_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Merge(m, src)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Size(m)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_JSONPayload proto.InternalMessageInfo

func (m *AnomalousIAMGrant_JSONPayload) GetAffectedResources() []*AnomalousIAMGrant_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetProperties() *AnomalousIAMGrant_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetDetectionCategory() *AnomalousIAMGrant_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIP struct {
	InsertId             string             `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string             `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *BadIP_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BadIP) Reset()         { *m = BadIP{} }
func (m *BadIP) String() string { return proto.CompactTextString(m) }
func (*BadIP) ProtoMessage()    {}
func (*BadIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2}
}

func (m *BadIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP.Unmarshal(m, b)
}
func (m *BadIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP.Marshal(b, m, deterministic)
}
func (m *BadIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP.Merge(m, src)
}
func (m *BadIP) XXX_Size() int {
	return xxx_messageInfo_BadIP.Size(m)
}
func (m *BadIP) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP proto.InternalMessageInfo

func (m *BadIP) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *BadIP) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *BadIP) GetJsonPayload() *BadIP_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type BadIP_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	InstanceDetails      string   `protobuf:"bytes,3,opt,name=instanceDetails,proto3" json:"instanceDetails,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_Properties) Reset()         { *m = BadIP_Properties{} }
func (m *BadIP_Properties) String() string { return proto.CompactTextString(m) }
func (*BadIP_Properties) ProtoMessage()    {}
func (*BadIP_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 0}
}

func (m *BadIP_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_Properties.Unmarshal(m, b)
}
func (m *BadIP_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_Properties.Marshal(b, m, deterministic)
}
func (m *BadIP_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_Properties.Merge(m, src)
}
func (m *BadIP_Properties) XXX_Size() int {
	return xxx_messageInfo_BadIP_Properties.Size(m)
}
func (m *BadIP_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_Properties proto.InternalMessageInfo

func (m *BadIP_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *BadIP_Properties) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *BadIP_Properties) GetInstanceDetails() string {
	if m != nil {
		return m.InstanceDetails
	}
	return ""
}

func (m *BadIP_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type BadIP_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_AffectedResource) Reset()         { *m = BadIP_AffectedResource{} }
func (m *BadIP_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*BadIP_AffectedResource) ProtoMessage()    {}
func (*BadIP_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 1}
}

func (m *BadIP_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_AffectedResource.Unmarshal(m, b)
}
func (m *BadIP_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_AffectedResource.Marshal(b, m, deterministic)
}
func (m *BadIP_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_AffectedResource.Merge(m, src)
}
func (m *BadIP_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_BadIP_AffectedResource.Size(m)
}
func (m *BadIP_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_AffectedResource proto.InternalMessageInfo

func (m *BadIP_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type BadIP_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_DetectionCategory) Reset()         { *m = BadIP_DetectionCategory{} }
func (m *BadIP_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*BadIP_DetectionCategory) ProtoMessage()    {}
func (*BadIP_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 2}
}

func (m *BadIP_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_DetectionCategory.Unmarshal(m, b)
}
func (m *BadIP_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *BadIP_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_DetectionCategory.Merge(m, src)
}
func (m *BadIP_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_BadIP_DetectionCategory.Size(m)
}
func (m *BadIP_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_DetectionCategory proto.InternalMessageInfo

func (m *BadIP_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type BadIP_JSONPayload struct {
	AffectedResources    []*BadIP_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *BadIP_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *BadIP_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BadIP_JSONPayload) Reset()         { *m = BadIP_JSONPayload{} }
func (m *BadIP_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*BadIP_JSONPayload) ProtoMessage()    {}
func (*BadIP_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 3}
}

func (m *BadIP_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_JSONPayload.Unmarshal(m, b)
}
func (m *BadIP_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_JSONPayload.Marshal(b, m, deterministic)
}
func (m *BadIP_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_JSONPayload.Merge(m, src)
}
func (m *BadIP_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_BadIP_JSONPayload.Size(m)
}
func (m *BadIP_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_JSONPayload proto.InternalMessageInfo

func (m *BadIP_JSONPayload) GetAffectedResources() []*BadIP_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *BadIP_JSONPayload) GetProperties() *BadIP_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BadIP_JSONPayload) GetDetectionCategory() *BadIP_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type SshBruteForce struct {
	InsertId             string                     `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                     `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *SshBruteForce_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SshBruteForce) Reset()         { *m = SshBruteForce{} }
func (m *SshBruteForce) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce) ProtoMessage()    {}
func (*SshBruteForce) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3}
}

func (m *SshBruteForce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce.Unmarshal(m, b)
}
func (m *SshBruteForce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce.Marshal(b, m, deterministic)
}
func (m *SshBruteForce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce.Merge(m, src)
}
func (m *SshBruteForce) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce.Size(m)
}
func (m *SshBruteForce) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce proto.InternalMessageInfo

func (m *SshBruteForce) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *SshBruteForce) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *SshBruteForce) GetJsonPayload() *SshBruteForce_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type SshBruteForce_LoginAttempt struct {
	AuthResult           string   `protobuf:"bytes,1,opt,name=authResult,proto3" json:"authResult,omitempty"`
	SourceIp             string   `protobuf:"bytes,2,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	VmName               string   `protobuf:"bytes,4,opt,name=vmName,proto3" json:"vmName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_LoginAttempt) Reset()         { *m = SshBruteForce_LoginAttempt{} }
func (m *SshBruteForce_LoginAttempt) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_LoginAttempt) ProtoMessage()    {}
func (*SshBruteForce_LoginAttempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 0}
}

func (m *SshBruteForce_LoginAttempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Unmarshal(m, b)
}
func (m *SshBruteForce_LoginAttempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_LoginAttempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_LoginAttempt.Merge(m, src)
}
func (m *SshBruteForce_LoginAttempt) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Size(m)
}
func (m *SshBruteForce_LoginAttempt) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_LoginAttempt.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_LoginAttempt proto.InternalMessageInfo

func (m *SshBruteForce_LoginAttempt) GetAuthResult() string {
	if m != nil {
		return m.AuthResult
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetVmName() string {
	if m != nil {
		return m.VmName
	}
	return ""
}

type SshBruteForce_Properties struct {
	InstanceId           string                        `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProjectId            string                        `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Zone                 string                        `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	LoginAttempts        []*SshBruteForce_LoginAttempt `protobuf:"bytes,4,rep,name=LoginAttempts,proto3" json:"LoginAttempts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SshBruteForce_Properties) Reset()         { *m = SshBruteForce_Properties{} }
func (m *SshBruteForce_Properties) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_Properties) ProtoMessage()    {}
func (*SshBruteForce_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 1}
}

func (m *SshBruteForce_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_Properties.Unmarshal(m, b)
}
func (m *SshBruteForce_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_Properties.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_Properties.Merge(m, src)
}
func (m *SshBruteForce_Properties) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_Properties.Size(m)
}
func (m *SshBruteForce_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_Properties proto.InternalMessageInfo

func (m *SshBruteForce_Properties) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *SshBruteForce_Properties) GetLoginAttempts() []*SshBruteForce_LoginAttempt {
	if m != nil {
		return m.LoginAttempts
	}
	return nil
}

type SshBruteForce_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_AffectedResource) Reset()         { *m = SshBruteForce_AffectedResource{} }
func (m *SshBruteForce_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_AffectedResource) ProtoMessage()    {}
func (*SshBruteForce_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 2}
}

func (m *SshBruteForce_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Unmarshal(m, b)
}
func (m *SshBruteForce_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_AffectedResource.Merge(m, src)
}
func (m *SshBruteForce_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Size(m)
}
func (m *SshBruteForce_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_AffectedResource proto.InternalMessageInfo

func (m *SshBruteForce_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type SshBruteForce_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_DetectionCategory) Reset()         { *m = SshBruteForce_DetectionCategory{} }
func (m *SshBruteForce_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_DetectionCategory) ProtoMessage()    {}
func (*SshBruteForce_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 3}
}

func (m *SshBruteForce_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Unmarshal(m, b)
}
func (m *SshBruteForce_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_DetectionCategory.Merge(m, src)
}
func (m *SshBruteForce_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Size(m)
}
func (m *SshBruteForce_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_DetectionCategory proto.InternalMessageInfo

func (m *SshBruteForce_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type SshBruteForce_JSONPayload struct {
	AffectedResources    []*SshBruteForce_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *SshBruteForce_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *SshBruteForce_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SshBruteForce_JSONPayload) Reset()         { *m = SshBruteForce_JSONPayload{} }
func (m *SshBruteForce_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_JSONPayload) ProtoMessage()    {}
func (*SshBruteForce_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 4}
}

func (m *SshBruteForce_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Unmarshal(m, b)
}
func (m *SshBruteForce_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_JSONPayload.Merge(m, src)
}
func (m *SshBruteForce_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Size(m)
}
func (m *SshBruteForce_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_JSONPayload proto.InternalMessageInfo

func (m *SshBruteForce_JSONPayload) GetAffectedResources() []*SshBruteForce_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetProperties() *SshBruteForce_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetDetectionCategory() *SshBruteForce_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIPSCC struct {
	NotificationConfigName string            `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *BadIPSCC_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *BadIPSCC) Reset()         { *m = BadIPSCC{} }
func (m *BadIPSCC) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC) ProtoMessage()    {}
func (*BadIPSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4}
}

func (m *BadIPSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC.Unmarshal(m, b)
}
func (m *BadIPSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC.Marshal(b, m, deterministic)
}
func (m *BadIPSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC.Merge(m, src)
}
func (m *BadIPSCC) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC.Size(m)
}
func (m *BadIPSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC proto.InternalMessageInfo

func (m *BadIPSCC) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *BadIPSCC) GetFinding() *BadIPSCC_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type BadIPSCC_SecurityMarks struct {
	Marks                map[string]string `protobuf:"bytes,1,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BadIPSCC_SecurityMarks) Reset()         { *m = BadIPSCC_SecurityMarks{} }
func (m *BadIPSCC_SecurityMarks) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_SecurityMarks) ProtoMessage()    {}
func (*BadIPSCC_SecurityMarks) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 0}
}

func (m *BadIPSCC_SecurityMarks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Unmarshal(m, b)
}
func (m *BadIPSCC_SecurityMarks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_SecurityMarks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_SecurityMarks.Merge(m, src)
}
func (m *BadIPSCC_SecurityMarks) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Size(m)
}
func (m *BadIPSCC_SecurityMarks) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_SecurityMarks.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_SecurityMarks proto.InternalMessageInfo

func (m *BadIPSCC_SecurityMarks) GetMarks() map[string]string {
	if m != nil {
		return m.Marks
	}
	return nil
}

type BadIPSCC_Network struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIPSCC_Network) Reset()         { *m = BadIPSCC_Network{} }
func (m *BadIPSCC_Network) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Network) ProtoMessage()    {}
func (*BadIPSCC_Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 1}
}

func (m *BadIPSCC_Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Network.Unmarshal(m, b)
}
func (m *BadIPSCC_Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Network.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Network.Merge(m, src)
}
func (m *BadIPSCC_Network) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Network.Size(m)
}
func (m *BadIPSCC_Network) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Network.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Network proto.InternalMessageInfo

func (m *BadIPSCC_Network) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

type BadIPSCC_Properties struct {
	Network              *BadIPSCC_Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	InstanceDetails      string            `protobuf:"bytes,2,opt,name=instanceDetails,proto3" json:"instanceDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BadIPSCC_Properties) Reset()         { *m = BadIPSCC_Properties{} }
func (m *BadIPSCC_Properties) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Properties) ProtoMessage()    {}
func (*BadIPSCC_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 2}
}

func (m *BadIPSCC_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Properties.Unmarshal(m, b)
}
func (m *BadIPSCC_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Properties.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Properties.Merge(m, src)
}
func (m *BadIPSCC_Properties) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Properties.Size(m)
}
func (m *BadIPSCC_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Properties proto.InternalMessageInfo

func (m *BadIPSCC_Properties) GetNetwork() *BadIPSCC_Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *BadIPSCC_Properties) GetInstanceDetails() string {
	if m != nil {
		return m.InstanceDetails
	}
	return ""
}

type BadIPSCC_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIPSCC_DetectionCategory) Reset()         { *m = BadIPSCC_DetectionCategory{} }
func (m *BadIPSCC_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_DetectionCategory) ProtoMessage()    {}
func (*BadIPSCC_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 3}
}

func (m *BadIPSCC_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Unmarshal(m, b)
}
func (m *BadIPSCC_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_DetectionCategory.Merge(m, src)
}
func (m *BadIPSCC_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Size(m)
}
func (m *BadIPSCC_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_DetectionCategory proto.InternalMessageInfo

func (m *BadIPSCC_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type BadIPSCC_SourceProperties struct {
	Properties           *BadIPSCC_Properties        `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *BadIPSCC_DetectionCategory `protobuf:"bytes,2,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BadIPSCC_SourceProperties) Reset()         { *m = BadIPSCC_SourceProperties{} }
func (m *BadIPSCC_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_SourceProperties) ProtoMessage()    {}
func (*BadIPSCC_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 4}
}

func (m *BadIPSCC_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Unmarshal(m, b)
}
func (m *BadIPSCC_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_SourceProperties.Merge(m, src)
}
func (m *BadIPSCC_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Size(m)
}
func (m *BadIPSCC_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_SourceProperties proto.InternalMessageInfo

func (m *BadIPSCC_SourceProperties) GetProperties() *BadIPSCC_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BadIPSCC_SourceProperties) GetDetectionCategory() *BadIPSCC_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIPSCC_Finding struct {
	SourceProperties     *BadIPSCC_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                     `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                     `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                     `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	SecurityMarks        *BadIPSCC_SecurityMarks    `protobuf:"bytes,5,opt,name=securityMarks,proto3" json:"securityMarks,omitempty"`
	EventTime            string                     `protobuf:"bytes,6,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	Name                 string                     `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BadIPSCC_Finding) Reset()         { *m = BadIPSCC_Finding{} }
func (m *BadIPSCC_Finding) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Finding) ProtoMessage()    {}
func (*BadIPSCC_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 5}
}

func (m *BadIPSCC_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Finding.Unmarshal(m, b)
}
func (m *BadIPSCC_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Finding.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Finding.Merge(m, src)
}
func (m *BadIPSCC_Finding) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Finding.Size(m)
}
func (m *BadIPSCC_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Finding proto.InternalMessageInfo

func (m *BadIPSCC_Finding) GetSourceProperties() *BadIPSCC_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *BadIPSCC_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *BadIPSCC_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *BadIPSCC_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *BadIPSCC_Finding) GetSecurityMarks() *BadIPSCC_SecurityMarks {
	if m != nil {
		return m.SecurityMarks
	}
	return nil
}

func (m *BadIPSCC_Finding) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *BadIPSCC_Finding) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AnomalousIAMGrantSCC struct {
	NotificationConfigName string                        `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *AnomalousIAMGrantSCC_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                      `json:"-"`
	XXX_unrecognized       []byte                        `json:"-"`
	XXX_sizecache          int32                         `json:"-"`
}

func (m *AnomalousIAMGrantSCC) Reset()         { *m = AnomalousIAMGrantSCC{} }
func (m *AnomalousIAMGrantSCC) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5}
}

func (m *AnomalousIAMGrantSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC.Size(m)
}
func (m *AnomalousIAMGrantSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *AnomalousIAMGrantSCC) GetFinding() *AnomalousIAMGrantSCC_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type AnomalousIAMGrantSCC_SecurityMarks struct {
	Marks                map[string]string `protobuf:"bytes,1,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AnomalousIAMGrantSCC_SecurityMarks) Reset()         { *m = AnomalousIAMGrantSCC_SecurityMarks{} }
func (m *AnomalousIAMGrantSCC_SecurityMarks) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_SecurityMarks) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_SecurityMarks) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 0}
}

func (m *AnomalousIAMGrantSCC_SecurityMarks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_SecurityMarks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_SecurityMarks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_SecurityMarks) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks.Size(m)
}
func (m *AnomalousIAMGrantSCC_SecurityMarks) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_SecurityMarks proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_SecurityMarks) GetMarks() map[string]string {
	if m != nil {
		return m.Marks
	}
	return nil
}

type AnomalousIAMGrantSCC_Resource struct {
	ProjectDisplayName   string   `protobuf:"bytes,1,opt,name=project_display_name,json=projectDisplayName,proto3" json:"project_display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_Resource) Reset()         { *m = AnomalousIAMGrantSCC_Resource{} }
func (m *AnomalousIAMGrantSCC_Resource) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_Resource) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_Resource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 1}
}

func (m *AnomalousIAMGrantSCC_Resource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Resource.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Resource.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_Resource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_Resource.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_Resource) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Resource.Size(m)
}
func (m *AnomalousIAMGrantSCC_Resource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_Resource.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_Resource proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_Resource) GetProjectDisplayName() string {
	if m != nil {
		return m.ProjectDisplayName
	}
	return ""
}

type AnomalousIAMGrantSCC_SourceLogId struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_SourceLogId) Reset()         { *m = AnomalousIAMGrantSCC_SourceLogId{} }
func (m *AnomalousIAMGrantSCC_SourceLogId) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_SourceLogId) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_SourceLogId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 2}
}

func (m *AnomalousIAMGrantSCC_SourceLogId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_SourceLogId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_SourceLogId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_SourceLogId) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId.Size(m)
}
func (m *AnomalousIAMGrantSCC_SourceLogId) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_SourceLogId proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_SourceLogId) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

type AnomalousIAMGrantSCC_Evidence struct {
	SourceLogId          *AnomalousIAMGrantSCC_SourceLogId `protobuf:"bytes,1,opt,name=sourceLogId,proto3" json:"sourceLogId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *AnomalousIAMGrantSCC_Evidence) Reset()         { *m = AnomalousIAMGrantSCC_Evidence{} }
func (m *AnomalousIAMGrantSCC_Evidence) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_Evidence) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_Evidence) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 3}
}

func (m *AnomalousIAMGrantSCC_Evidence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Evidence.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_Evidence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Evidence.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_Evidence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_Evidence.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_Evidence) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Evidence.Size(m)
}
func (m *AnomalousIAMGrantSCC_Evidence) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_Evidence.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_Evidence proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_Evidence) GetSourceLogId() *AnomalousIAMGrantSCC_SourceLogId {
	if m != nil {
		return m.SourceLogId
	}
	return nil
}

type AnomalousIAMGrantSCC_SourceId struct {
	ProjectNumber        string   `protobuf:"bytes,1,opt,name=projectNumber,proto3" json:"projectNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_SourceId) Reset()         { *m = AnomalousIAMGrantSCC_SourceId{} }
func (m *AnomalousIAMGrantSCC_SourceId) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_SourceId) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_SourceId) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 4}
}

func (m *AnomalousIAMGrantSCC_SourceId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceId.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_SourceId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceId.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_SourceId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceId.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_SourceId) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceId.Size(m)
}
func (m *AnomalousIAMGrantSCC_SourceId) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceId.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_SourceId proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_SourceId) GetProjectNumber() string {
	if m != nil {
		return m.ProjectNumber
	}
	return ""
}

type AnomalousIAMGrantSCC_SensitiveRoleGrant struct {
	Members              []string `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) Reset() {
	*m = AnomalousIAMGrantSCC_SensitiveRoleGrant{}
}
func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_SensitiveRoleGrant) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_SensitiveRoleGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 5}
}

func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant.Size(m)
}
func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_SensitiveRoleGrant proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_SensitiveRoleGrant) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

type AnomalousIAMGrantSCC_Properties struct {
	SensitiveRoleGrant   *AnomalousIAMGrantSCC_SensitiveRoleGrant `protobuf:"bytes,1,opt,name=sensitiveRoleGrant,proto3" json:"sensitiveRoleGrant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                 `json:"-"`
	XXX_unrecognized     []byte                                   `json:"-"`
	XXX_sizecache        int32                                    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_Properties) Reset()         { *m = AnomalousIAMGrantSCC_Properties{} }
func (m *AnomalousIAMGrantSCC_Properties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_Properties) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 6}
}

func (m *AnomalousIAMGrantSCC_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Properties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Properties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_Properties.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_Properties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Properties.Size(m)
}
func (m *AnomalousIAMGrantSCC_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_Properties proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_Properties) GetSensitiveRoleGrant() *AnomalousIAMGrantSCC_SensitiveRoleGrant {
	if m != nil {
		return m.SensitiveRoleGrant
	}
	return nil
}

type AnomalousIAMGrantSCC_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrantSCC_DetectionCategory) Reset() {
	*m = AnomalousIAMGrantSCC_DetectionCategory{}
}
func (m *AnomalousIAMGrantSCC_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_DetectionCategory) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 7}
}

func (m *AnomalousIAMGrantSCC_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory.Size(m)
}
func (m *AnomalousIAMGrantSCC_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_DetectionCategory proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type AnomalousIAMGrantSCC_SourceProperties struct {
	Properties           *AnomalousIAMGrantSCC_Properties        `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *AnomalousIAMGrantSCC_DetectionCategory `protobuf:"bytes,2,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	SourceId             *AnomalousIAMGrantSCC_SourceId          `protobuf:"bytes,3,opt,name=sourceId,proto3" json:"sourceId,omitempty"`
	Evidence             []*AnomalousIAMGrantSCC_Evidence        `protobuf:"bytes,4,rep,name=evidence,proto3" json:"evidence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *AnomalousIAMGrantSCC_SourceProperties) Reset()         { *m = AnomalousIAMGrantSCC_SourceProperties{} }
func (m *AnomalousIAMGrantSCC_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_SourceProperties) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 8}
}

func (m *AnomalousIAMGrantSCC_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties.Size(m)
}
func (m *AnomalousIAMGrantSCC_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_SourceProperties proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_SourceProperties) GetProperties() *AnomalousIAMGrantSCC_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnomalousIAMGrantSCC_SourceProperties) GetDetectionCategory() *AnomalousIAMGrantSCC_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

func (m *AnomalousIAMGrantSCC_SourceProperties) GetSourceId() *AnomalousIAMGrantSCC_SourceId {
	if m != nil {
		return m.SourceId
	}
	return nil
}

func (m *AnomalousIAMGrantSCC_SourceProperties) GetEvidence() []*AnomalousIAMGrantSCC_Evidence {
	if m != nil {
		return m.Evidence
	}
	return nil
}

type AnomalousIAMGrantSCC_Finding struct {
	SourceProperties     *AnomalousIAMGrantSCC_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                                 `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	SecurityMarks        *AnomalousIAMGrantSCC_SecurityMarks    `protobuf:"bytes,5,opt,name=securityMarks,proto3" json:"securityMarks,omitempty"`
	EventTime            string                                 `protobuf:"bytes,6,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	Name                 string                                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Resource             *AnomalousIAMGrantSCC_Resource         `protobuf:"bytes,8,opt,name=resource,proto3" json:"resource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *AnomalousIAMGrantSCC_Finding) Reset()         { *m = AnomalousIAMGrantSCC_Finding{} }
func (m *AnomalousIAMGrantSCC_Finding) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrantSCC_Finding) ProtoMessage()    {}
func (*AnomalousIAMGrantSCC_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{5, 9}
}

func (m *AnomalousIAMGrantSCC_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Finding.Unmarshal(m, b)
}
func (m *AnomalousIAMGrantSCC_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Finding.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrantSCC_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrantSCC_Finding.Merge(m, src)
}
func (m *AnomalousIAMGrantSCC_Finding) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrantSCC_Finding.Size(m)
}
func (m *AnomalousIAMGrantSCC_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrantSCC_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrantSCC_Finding proto.InternalMessageInfo

func (m *AnomalousIAMGrantSCC_Finding) GetSourceProperties() *AnomalousIAMGrantSCC_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *AnomalousIAMGrantSCC_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *AnomalousIAMGrantSCC_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *AnomalousIAMGrantSCC_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AnomalousIAMGrantSCC_Finding) GetSecurityMarks() *AnomalousIAMGrantSCC_SecurityMarks {
	if m != nil {
		return m.SecurityMarks
	}
	return nil
}

func (m *AnomalousIAMGrantSCC_Finding) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *AnomalousIAMGrantSCC_Finding) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AnomalousIAMGrantSCC_Finding) GetResource() *AnomalousIAMGrantSCC_Resource {
	if m != nil {
		return m.Resource
	}
	return nil
}

func init() {
	proto.RegisterType((*BadDomain)(nil), "BadDomain")
	proto.RegisterType((*AnomalousIAMGrant)(nil), "AnomalousIAMGrant")
	proto.RegisterType((*AnomalousIAMGrant_Properties)(nil), "AnomalousIAMGrant.Properties")
	proto.RegisterType((*AnomalousIAMGrant_AffectedResource)(nil), "AnomalousIAMGrant.AffectedResource")
	proto.RegisterType((*AnomalousIAMGrant_DetectionCategory)(nil), "AnomalousIAMGrant.DetectionCategory")
	proto.RegisterType((*AnomalousIAMGrant_JSONPayload)(nil), "AnomalousIAMGrant.JSONPayload")
	proto.RegisterType((*BadIP)(nil), "BadIP")
	proto.RegisterType((*BadIP_Properties)(nil), "BadIP.Properties")
	proto.RegisterType((*BadIP_AffectedResource)(nil), "BadIP.AffectedResource")
	proto.RegisterType((*BadIP_DetectionCategory)(nil), "BadIP.DetectionCategory")
	proto.RegisterType((*BadIP_JSONPayload)(nil), "BadIP.JSONPayload")
	proto.RegisterType((*SshBruteForce)(nil), "SshBruteForce")
	proto.RegisterType((*SshBruteForce_LoginAttempt)(nil), "SshBruteForce.LoginAttempt")
	proto.RegisterType((*SshBruteForce_Properties)(nil), "SshBruteForce.Properties")
	proto.RegisterType((*SshBruteForce_AffectedResource)(nil), "SshBruteForce.AffectedResource")
	proto.RegisterType((*SshBruteForce_DetectionCategory)(nil), "SshBruteForce.DetectionCategory")
	proto.RegisterType((*SshBruteForce_JSONPayload)(nil), "SshBruteForce.JSONPayload")
	proto.RegisterType((*BadIPSCC)(nil), "BadIPSCC")
	proto.RegisterType((*BadIPSCC_SecurityMarks)(nil), "BadIPSCC.SecurityMarks")
	proto.RegisterMapType((map[string]string)(nil), "BadIPSCC.SecurityMarks.MarksEntry")
	proto.RegisterType((*BadIPSCC_Network)(nil), "BadIPSCC.Network")
	proto.RegisterType((*BadIPSCC_Properties)(nil), "BadIPSCC.Properties")
	proto.RegisterType((*BadIPSCC_DetectionCategory)(nil), "BadIPSCC.DetectionCategory")
	proto.RegisterType((*BadIPSCC_SourceProperties)(nil), "BadIPSCC.SourceProperties")
	proto.RegisterType((*BadIPSCC_Finding)(nil), "BadIPSCC.Finding")
	proto.RegisterType((*AnomalousIAMGrantSCC)(nil), "AnomalousIAMGrantSCC")
	proto.RegisterType((*AnomalousIAMGrantSCC_SecurityMarks)(nil), "AnomalousIAMGrantSCC.SecurityMarks")
	proto.RegisterMapType((map[string]string)(nil), "AnomalousIAMGrantSCC.SecurityMarks.MarksEntry")
	proto.RegisterType((*AnomalousIAMGrantSCC_Resource)(nil), "AnomalousIAMGrantSCC.Resource")
	proto.RegisterType((*AnomalousIAMGrantSCC_SourceLogId)(nil), "AnomalousIAMGrantSCC.SourceLogId")
	proto.RegisterType((*AnomalousIAMGrantSCC_Evidence)(nil), "AnomalousIAMGrantSCC.Evidence")
	proto.RegisterType((*AnomalousIAMGrantSCC_SourceId)(nil), "AnomalousIAMGrantSCC.SourceId")
	proto.RegisterType((*AnomalousIAMGrantSCC_SensitiveRoleGrant)(nil), "AnomalousIAMGrantSCC.SensitiveRoleGrant")
	proto.RegisterType((*AnomalousIAMGrantSCC_Properties)(nil), "AnomalousIAMGrantSCC.Properties")
	proto.RegisterType((*AnomalousIAMGrantSCC_DetectionCategory)(nil), "AnomalousIAMGrantSCC.DetectionCategory")
	proto.RegisterType((*AnomalousIAMGrantSCC_SourceProperties)(nil), "AnomalousIAMGrantSCC.SourceProperties")
	proto.RegisterType((*AnomalousIAMGrantSCC_Finding)(nil), "AnomalousIAMGrantSCC.Finding")
}

func init() { proto.RegisterFile("etd/protos/etd.proto", fileDescriptor_7762cc4b80af3525) }

var fileDescriptor_7762cc4b80af3525 = []byte{
	// 1196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x98, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xc0, 0x65, 0xe7, 0x8f, 0xed, 0xe7, 0x46, 0x24, 0xa3, 0xa8, 0x5d, 0xb6, 0xb4, 0x35, 0x4e,
	0x05, 0x16, 0x91, 0x9c, 0x12, 0x2a, 0x08, 0x55, 0x2a, 0xd5, 0x71, 0x12, 0xb4, 0xa8, 0x49, 0xd3,
	0x31, 0x95, 0xb8, 0x45, 0x9b, 0xdd, 0xb1, 0xbb, 0xcd, 0x7a, 0xc6, 0xda, 0x99, 0x0d, 0x98, 0x03,
	0x07, 0x10, 0x67, 0x0e, 0x5c, 0xb8, 0xf7, 0x6b, 0xf0, 0x1d, 0xf8, 0x0c, 0x1c, 0x10, 0x42, 0xe2,
	0xc6, 0x17, 0x40, 0xbb, 0x33, 0xfb, 0xd7, 0xbb, 0x91, 0xd3, 0x08, 0xb8, 0x44, 0xfb, 0xde, 0xbc,
	0xf7, 0xf6, 0xcd, 0x9b, 0xdf, 0x7b, 0x9e, 0x0d, 0xac, 0x13, 0x61, 0x6f, 0x4d, 0x3c, 0x26, 0x18,
	0xdf, 0x22, 0xc2, 0xee, 0x86, 0x8f, 0xed, 0x0f, 0xa0, 0xb1, 0x67, 0xda, 0xfb, 0x6c, 0x6c, 0x3a,
	0x14, 0xdd, 0x01, 0x70, 0x26, 0xa7, 0xa6, 0x6d, 0x7b, 0x84, 0x73, 0xad, 0xd2, 0xaa, 0x74, 0x1a,
	0xb8, 0xe1, 0x4c, 0x7a, 0x52, 0xd1, 0xfe, 0x73, 0x11, 0xd6, 0x7a, 0x94, 0x8d, 0x4d, 0x97, 0xf9,
	0xdc, 0xe8, 0x1d, 0x7d, 0xe6, 0x99, 0x54, 0x20, 0x1d, 0xea, 0x0e, 0xe5, 0xc4, 0x13, 0x86, 0xad,
	0x5c, 0x62, 0x19, 0x69, 0x50, 0x73, 0xd9, 0xe8, 0xd8, 0x1c, 0x13, 0xad, 0x1a, 0x2e, 0x45, 0x22,
	0x7a, 0x02, 0xcd, 0x57, 0x9c, 0xd1, 0x13, 0x73, 0xea, 0x32, 0xd3, 0xd6, 0x16, 0x5a, 0x95, 0x4e,
	0x73, 0xfb, 0x6e, 0x77, 0x26, 0x7c, 0xf7, 0xf3, 0xc1, 0xb3, 0x63, 0x65, 0x85, 0xd3, 0x2e, 0xfa,
	0x0b, 0x80, 0x13, 0x8f, 0x4d, 0x88, 0x27, 0x1c, 0xc2, 0x83, 0xd4, 0x27, 0x1e, 0x7b, 0x45, 0x2c,
	0x71, 0xea, 0x44, 0x79, 0x34, 0x94, 0xc6, 0xb0, 0x51, 0x07, 0xde, 0x22, 0x5f, 0x0b, 0xe2, 0x51,
	0xd3, 0x3d, 0x22, 0xe3, 0x33, 0xe2, 0x71, 0xad, 0xda, 0x5a, 0xe8, 0x34, 0x70, 0x5e, 0xad, 0xef,
	0xc2, 0x6a, 0x6f, 0x38, 0x24, 0x96, 0x20, 0x36, 0x26, 0x9c, 0xf9, 0x9e, 0x45, 0x02, 0xef, 0x91,
	0x35, 0x89, 0xc4, 0x70, 0x3b, 0xf2, 0x0d, 0x79, 0xb5, 0xfe, 0x1c, 0xd6, 0xf6, 0x89, 0x20, 0x96,
	0x70, 0x18, 0xed, 0x9b, 0x82, 0x8c, 0x98, 0x37, 0x0d, 0x2a, 0xe4, 0xf9, 0x6e, 0xda, 0x2f, 0x96,
	0x51, 0x0b, 0x9a, 0xdc, 0x3f, 0xc3, 0xd1, 0xb2, 0xac, 0x52, 0x5a, 0xa5, 0xff, 0x5d, 0x81, 0x66,
	0xaa, 0x08, 0xe8, 0x39, 0xac, 0x99, 0xb9, 0x04, 0x83, 0xb3, 0x5a, 0xe8, 0x34, 0xb7, 0x37, 0x0a,
	0xea, 0x97, 0xdf, 0x0c, 0x9e, 0xf5, 0x46, 0x8f, 0xc3, 0xe2, 0xa9, 0x52, 0x86, 0x39, 0x34, 0xb7,
	0xef, 0x14, 0xc4, 0x4a, 0xea, 0x8d, 0x53, 0x0e, 0x08, 0xc3, 0x9a, 0x9d, 0xdf, 0xb4, 0x3a, 0xd1,
	0xfb, 0x05, 0x51, 0x66, 0x0a, 0x84, 0x67, 0xdd, 0xdb, 0xbf, 0x2c, 0xc2, 0xd2, 0x9e, 0x69, 0x1b,
	0x27, 0x6f, 0xc8, 0xd7, 0xc3, 0x22, 0xbe, 0x50, 0x37, 0x0c, 0x59, 0xce, 0xd4, 0x0f, 0x95, 0xab,
	0x40, 0xa5, 0x43, 0xdd, 0x65, 0x96, 0x19, 0xe4, 0xad, 0x5e, 0x1f, 0xcb, 0x01, 0x32, 0x0e, 0xe5,
	0xc2, 0xa4, 0x16, 0xd9, 0x27, 0xc2, 0x74, 0x5c, 0x1e, 0xe6, 0xd0, 0xc0, 0x79, 0x35, 0x42, 0xb0,
	0xf8, 0x0d, 0xa3, 0x44, 0x5b, 0x0c, 0x97, 0xc3, 0xe7, 0x6b, 0x42, 0xb8, 0x75, 0x45, 0x08, 0xf5,
	0x5f, 0x73, 0x88, 0x1d, 0x94, 0x23, 0x76, 0x4b, 0x95, 0x70, 0x1e, 0xac, 0x3e, 0x2c, 0xc0, 0x6a,
	0x4d, 0xf9, 0x97, 0xa0, 0x74, 0x58, 0x8e, 0x92, 0xa6, 0x3c, 0xe7, 0xc2, 0xe7, 0xbb, 0x65, 0x58,
	0x19, 0xf0, 0x97, 0x7b, 0x9e, 0x2f, 0xc8, 0x21, 0x0b, 0xca, 0xf7, 0x66, 0x18, 0xed, 0x16, 0x61,
	0xa4, 0x77, 0x33, 0xa1, 0xcb, 0x71, 0xfa, 0x16, 0x6e, 0x3c, 0x65, 0x23, 0x87, 0xf6, 0x84, 0x20,
	0xe3, 0x89, 0x40, 0x77, 0x01, 0x4c, 0x5f, 0xbc, 0xc4, 0x84, 0xfb, 0xae, 0x50, 0x59, 0xa4, 0x34,
	0x41, 0x8e, 0xb2, 0x76, 0xc6, 0x24, 0x02, 0x2a, 0x92, 0x83, 0x35, 0x9f, 0x13, 0x2f, 0x4c, 0x52,
	0x92, 0x14, 0xcb, 0xe8, 0x26, 0x2c, 0x5f, 0x8c, 0xc3, 0x15, 0x09, 0x91, 0x92, 0xf4, 0xd7, 0x59,
	0x9c, 0xef, 0x41, 0x33, 0x82, 0x2f, 0xe1, 0x19, 0x22, 0x95, 0x61, 0xe7, 0x78, 0xaf, 0xe6, 0x79,
	0x8f, 0x48, 0x5d, 0x48, 0x48, 0x45, 0x3d, 0x58, 0x49, 0x6f, 0x91, 0x6b, 0x8b, 0x21, 0x26, 0xb7,
	0x73, 0x25, 0x4a, 0xdb, 0xe0, 0xac, 0xc7, 0x7f, 0x0d, 0xfb, 0x1f, 0x39, 0xd8, 0x8f, 0xca, 0x61,
	0xbf, 0x97, 0xdb, 0xc5, 0x3c, 0xd0, 0x7f, 0x5a, 0x00, 0xfd, 0xdb, 0xb9, 0x38, 0x25, 0xf0, 0x1f,
	0x97, 0xc3, 0xdf, 0xca, 0x45, 0x98, 0xab, 0x09, 0x7e, 0x5b, 0x86, 0x7a, 0xd8, 0x33, 0x83, 0x7e,
	0x1f, 0x7d, 0x0c, 0x37, 0x29, 0x13, 0xce, 0xd0, 0x91, 0x03, 0xaa, 0xcf, 0xe8, 0xd0, 0x19, 0xa5,
	0x0a, 0x54, 0xb2, 0x8a, 0x36, 0xa1, 0x36, 0x74, 0xa8, 0xed, 0xd0, 0x51, 0xb6, 0x83, 0x07, 0xfd,
	0x7e, 0xf7, 0x50, 0x2e, 0xe0, 0xc8, 0x42, 0xff, 0xbe, 0x02, 0x2b, 0x03, 0x62, 0xf9, 0x9e, 0x23,
	0xa6, 0x47, 0xa6, 0x77, 0xce, 0xd1, 0x0e, 0x2c, 0x8d, 0x83, 0x07, 0x55, 0xd1, 0x76, 0xe2, 0x9c,
	0xb1, 0xeb, 0x86, 0x7f, 0x0f, 0xa8, 0xf0, 0xa6, 0x58, 0x3a, 0xe8, 0x3b, 0x00, 0x89, 0x12, 0xad,
	0xc2, 0xc2, 0x39, 0x99, 0xaa, 0x5c, 0x83, 0x47, 0xb4, 0x0e, 0x4b, 0x17, 0xa6, 0xeb, 0x47, 0x2d,
	0x2b, 0x85, 0x47, 0xd5, 0x9d, 0x8a, 0xbe, 0x01, 0xb5, 0x63, 0x22, 0xbe, 0x62, 0xde, 0x79, 0xd0,
	0xd9, 0x8a, 0x5f, 0xe5, 0x1a, 0x89, 0xba, 0x95, 0x69, 0x8d, 0x4d, 0xa8, 0x51, 0xe9, 0x12, 0xda,
	0x65, 0x76, 0xa9, 0x62, 0xe1, 0xc8, 0xa2, 0x68, 0xb6, 0x57, 0x0b, 0x67, 0xfb, 0xd5, 0xe1, 0xfc,
	0xa9, 0x02, 0xab, 0x83, 0x90, 0xa4, 0x54, 0x72, 0x0f, 0x33, 0x48, 0xc9, 0xfc, 0xd6, 0x93, 0xfc,
	0x4a, 0x68, 0x32, 0x8a, 0x68, 0x92, 0x47, 0x78, 0x3b, 0x71, 0x9e, 0x07, 0x24, 0xfd, 0xe7, 0x2a,
	0xd4, 0xd4, 0x59, 0xa3, 0x43, 0x58, 0xe5, 0xb9, 0x04, 0x55, 0x4a, 0x7a, 0xea, 0x6c, 0x73, 0x16,
	0x78, 0xc6, 0x27, 0xa8, 0x82, 0x95, 0xce, 0xaa, 0x81, 0x63, 0x19, 0xb5, 0xe1, 0x86, 0x97, 0x6e,
	0x7d, 0x39, 0x70, 0x32, 0xba, 0xe0, 0xf8, 0xb9, 0x30, 0x45, 0x34, 0xf2, 0xa4, 0x80, 0x1e, 0xc3,
	0x0a, 0x4f, 0x73, 0xa5, 0x2d, 0x85, 0xa9, 0xdd, 0x2a, 0xc1, 0x0e, 0x67, 0xad, 0xd1, 0x3b, 0xd0,
	0x20, 0x17, 0x84, 0x8a, 0x2f, 0x9c, 0x31, 0xd1, 0x96, 0xe5, 0xfc, 0x8b, 0x15, 0xc1, 0xfc, 0xa3,
	0x41, 0x3a, 0x35, 0x39, 0xff, 0x82, 0xe7, 0xf6, 0xef, 0x00, 0xeb, 0x33, 0x57, 0x9c, 0xeb, 0xf4,
	0xdb, 0x27, 0xf9, 0x7e, 0x2b, 0xb8, 0x88, 0x15, 0xf6, 0xde, 0x8f, 0x33, 0xbd, 0xb7, 0x9f, 0xed,
	0xbd, 0x6e, 0x71, 0xa0, 0x7f, 0xaf, 0x0f, 0x77, 0xa1, 0x1e, 0x0f, 0xf4, 0x07, 0xb0, 0x1e, 0xfd,
	0xb4, 0xd8, 0x0e, 0x9f, 0xb8, 0xe6, 0xf4, 0x94, 0x26, 0xc5, 0x40, 0x6a, 0x6d, 0x5f, 0x2e, 0x85,
	0xad, 0xb0, 0x09, 0x4d, 0x89, 0xd1, 0x53, 0x36, 0x32, 0xec, 0xe0, 0x68, 0xe2, 0x5f, 0xa2, 0x99,
	0xab, 0x98, 0xfe, 0x0c, 0xea, 0x07, 0x17, 0x8e, 0x4d, 0xa8, 0x45, 0x50, 0x1f, 0x9a, 0x3c, 0x71,
	0x54, 0x70, 0xbe, 0x5b, 0xb2, 0xf9, 0xc4, 0x10, 0xa7, 0xbd, 0xf4, 0x07, 0x50, 0x97, 0x6b, 0x86,
	0x8d, 0xee, 0xc3, 0x8a, 0x7a, 0xd3, 0xb1, 0x1f, 0x7c, 0x24, 0xa8, 0xd7, 0x67, 0x95, 0x7a, 0x17,
	0xd0, 0x80, 0x50, 0xee, 0x08, 0xe7, 0x82, 0x60, 0xe6, 0x12, 0xf9, 0x75, 0xa4, 0x41, 0x6d, 0xac,
	0x3e, 0x38, 0x2a, 0xe1, 0x07, 0x47, 0x24, 0xea, 0xc3, 0xcc, 0x00, 0xfa, 0x12, 0x10, 0x9f, 0xf1,
	0x56, 0xb9, 0x77, 0xca, 0x0e, 0x2e, 0x6f, 0x8f, 0x0b, 0x62, 0x5c, 0x7d, 0x06, 0xbd, 0xae, 0x16,
	0xcc, 0xa0, 0x27, 0x05, 0x33, 0xa8, 0x55, 0x9c, 0x57, 0xc9, 0x3c, 0x7a, 0x51, 0x3e, 0x8f, 0xde,
	0x2f, 0x0e, 0x34, 0xcf, 0x6c, 0x42, 0x8f, 0xe2, 0x3b, 0xd3, 0x25, 0x5f, 0x91, 0xc9, 0x51, 0x1b,
	0x76, 0x7c, 0xa7, 0xb2, 0x03, 0x5f, 0xa2, 0xa8, 0x51, 0xf7, 0x96, 0x12, 0xdf, 0x88, 0x2d, 0x1c,
	0xdb, 0xeb, 0x7f, 0xa5, 0x66, 0x22, 0x2e, 0x9d, 0x89, 0xef, 0x5d, 0x96, 0xcb, 0xff, 0x30, 0x1f,
	0x8d, 0xe2, 0xf9, 0xb8, 0x31, 0xc7, 0x68, 0xb8, 0xf6, 0xac, 0x0c, 0xca, 0x1d, 0xa5, 0xa8, 0xd5,
	0x2f, 0x3b, 0xaa, 0xf8, 0x7e, 0x15, 0xdb, 0x9f, 0x2d, 0x87, 0xff, 0xae, 0xf8, 0xe8, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xc9, 0xfd, 0xf1, 0xba, 0xc6, 0x10, 0x00, 0x00,
}
