// Code generated by protoc-gen-go. DO NOT EDIT.
// source: etd/protos/etd.proto

package etd

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Finish.
type BadDomain struct {
	IpAddress            string   `protobuf:"bytes,1,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadDomain) Reset()         { *m = BadDomain{} }
func (m *BadDomain) String() string { return proto.CompactTextString(m) }
func (*BadDomain) ProtoMessage()    {}
func (*BadDomain) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{0}
}

func (m *BadDomain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadDomain.Unmarshal(m, b)
}
func (m *BadDomain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadDomain.Marshal(b, m, deterministic)
}
func (m *BadDomain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadDomain.Merge(m, src)
}
func (m *BadDomain) XXX_Size() int {
	return xxx_messageInfo_BadDomain.Size(m)
}
func (m *BadDomain) XXX_DiscardUnknown() {
	xxx_messageInfo_BadDomain.DiscardUnknown(m)
}

var xxx_messageInfo_BadDomain proto.InternalMessageInfo

func (m *BadDomain) GetIpAddress() string {
	if m != nil {
		return m.IpAddress
	}
	return ""
}

type AnomalousIAMGrant struct {
	InsertId             string                         `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                         `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *AnomalousIAMGrant_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *AnomalousIAMGrant) Reset()         { *m = AnomalousIAMGrant{} }
func (m *AnomalousIAMGrant) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant) ProtoMessage()    {}
func (*AnomalousIAMGrant) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1}
}

func (m *AnomalousIAMGrant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant.Merge(m, src)
}
func (m *AnomalousIAMGrant) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant.Size(m)
}
func (m *AnomalousIAMGrant) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant proto.InternalMessageInfo

func (m *AnomalousIAMGrant) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *AnomalousIAMGrant) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *AnomalousIAMGrant) GetJsonPayload() *AnomalousIAMGrant_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type AnomalousIAMGrant_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	ExternalMembers      []string `protobuf:"bytes,2,rep,name=externalMembers,proto3" json:"externalMembers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_Properties) Reset()         { *m = AnomalousIAMGrant_Properties{} }
func (m *AnomalousIAMGrant_Properties) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_Properties) ProtoMessage()    {}
func (*AnomalousIAMGrant_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 0}
}

func (m *AnomalousIAMGrant_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_Properties.Merge(m, src)
}
func (m *AnomalousIAMGrant_Properties) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_Properties.Size(m)
}
func (m *AnomalousIAMGrant_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_Properties proto.InternalMessageInfo

func (m *AnomalousIAMGrant_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *AnomalousIAMGrant_Properties) GetExternalMembers() []string {
	if m != nil {
		return m.ExternalMembers
	}
	return nil
}

type AnomalousIAMGrant_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_AffectedResource) Reset()         { *m = AnomalousIAMGrant_AffectedResource{} }
func (m *AnomalousIAMGrant_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_AffectedResource) ProtoMessage()    {}
func (*AnomalousIAMGrant_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 1}
}

func (m *AnomalousIAMGrant_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Merge(m, src)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_AffectedResource.Size(m)
}
func (m *AnomalousIAMGrant_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_AffectedResource proto.InternalMessageInfo

func (m *AnomalousIAMGrant_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type AnomalousIAMGrant_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	SubRuleName          string   `protobuf:"bytes,2,opt,name=subRuleName,proto3" json:"subRuleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnomalousIAMGrant_DetectionCategory) Reset()         { *m = AnomalousIAMGrant_DetectionCategory{} }
func (m *AnomalousIAMGrant_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_DetectionCategory) ProtoMessage()    {}
func (*AnomalousIAMGrant_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 2}
}

func (m *AnomalousIAMGrant_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Merge(m, src)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.Size(m)
}
func (m *AnomalousIAMGrant_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_DetectionCategory proto.InternalMessageInfo

func (m *AnomalousIAMGrant_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

func (m *AnomalousIAMGrant_DetectionCategory) GetSubRuleName() string {
	if m != nil {
		return m.SubRuleName
	}
	return ""
}

type AnomalousIAMGrant_JSONPayload struct {
	AffectedResources    []*AnomalousIAMGrant_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *AnomalousIAMGrant_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *AnomalousIAMGrant_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *AnomalousIAMGrant_JSONPayload) Reset()         { *m = AnomalousIAMGrant_JSONPayload{} }
func (m *AnomalousIAMGrant_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*AnomalousIAMGrant_JSONPayload) ProtoMessage()    {}
func (*AnomalousIAMGrant_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{1, 3}
}

func (m *AnomalousIAMGrant_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Unmarshal(m, b)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Marshal(b, m, deterministic)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Merge(m, src)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_AnomalousIAMGrant_JSONPayload.Size(m)
}
func (m *AnomalousIAMGrant_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_AnomalousIAMGrant_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_AnomalousIAMGrant_JSONPayload proto.InternalMessageInfo

func (m *AnomalousIAMGrant_JSONPayload) GetAffectedResources() []*AnomalousIAMGrant_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetProperties() *AnomalousIAMGrant_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *AnomalousIAMGrant_JSONPayload) GetDetectionCategory() *AnomalousIAMGrant_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIP struct {
	InsertId             string             `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string             `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *BadIP_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BadIP) Reset()         { *m = BadIP{} }
func (m *BadIP) String() string { return proto.CompactTextString(m) }
func (*BadIP) ProtoMessage()    {}
func (*BadIP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2}
}

func (m *BadIP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP.Unmarshal(m, b)
}
func (m *BadIP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP.Marshal(b, m, deterministic)
}
func (m *BadIP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP.Merge(m, src)
}
func (m *BadIP) XXX_Size() int {
	return xxx_messageInfo_BadIP.Size(m)
}
func (m *BadIP) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP proto.InternalMessageInfo

func (m *BadIP) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *BadIP) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *BadIP) GetJsonPayload() *BadIP_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type BadIP_Properties struct {
	ProjectId            string   `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	InstanceDetails      string   `protobuf:"bytes,3,opt,name=instanceDetails,proto3" json:"instanceDetails,omitempty"`
	Zone                 string   `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_Properties) Reset()         { *m = BadIP_Properties{} }
func (m *BadIP_Properties) String() string { return proto.CompactTextString(m) }
func (*BadIP_Properties) ProtoMessage()    {}
func (*BadIP_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 0}
}

func (m *BadIP_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_Properties.Unmarshal(m, b)
}
func (m *BadIP_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_Properties.Marshal(b, m, deterministic)
}
func (m *BadIP_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_Properties.Merge(m, src)
}
func (m *BadIP_Properties) XXX_Size() int {
	return xxx_messageInfo_BadIP_Properties.Size(m)
}
func (m *BadIP_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_Properties proto.InternalMessageInfo

func (m *BadIP_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *BadIP_Properties) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *BadIP_Properties) GetInstanceDetails() string {
	if m != nil {
		return m.InstanceDetails
	}
	return ""
}

func (m *BadIP_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

type BadIP_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_AffectedResource) Reset()         { *m = BadIP_AffectedResource{} }
func (m *BadIP_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*BadIP_AffectedResource) ProtoMessage()    {}
func (*BadIP_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 1}
}

func (m *BadIP_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_AffectedResource.Unmarshal(m, b)
}
func (m *BadIP_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_AffectedResource.Marshal(b, m, deterministic)
}
func (m *BadIP_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_AffectedResource.Merge(m, src)
}
func (m *BadIP_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_BadIP_AffectedResource.Size(m)
}
func (m *BadIP_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_AffectedResource proto.InternalMessageInfo

func (m *BadIP_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type BadIP_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIP_DetectionCategory) Reset()         { *m = BadIP_DetectionCategory{} }
func (m *BadIP_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*BadIP_DetectionCategory) ProtoMessage()    {}
func (*BadIP_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 2}
}

func (m *BadIP_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_DetectionCategory.Unmarshal(m, b)
}
func (m *BadIP_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *BadIP_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_DetectionCategory.Merge(m, src)
}
func (m *BadIP_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_BadIP_DetectionCategory.Size(m)
}
func (m *BadIP_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_DetectionCategory proto.InternalMessageInfo

func (m *BadIP_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type BadIP_JSONPayload struct {
	AffectedResources    []*BadIP_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *BadIP_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *BadIP_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *BadIP_JSONPayload) Reset()         { *m = BadIP_JSONPayload{} }
func (m *BadIP_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*BadIP_JSONPayload) ProtoMessage()    {}
func (*BadIP_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{2, 3}
}

func (m *BadIP_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIP_JSONPayload.Unmarshal(m, b)
}
func (m *BadIP_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIP_JSONPayload.Marshal(b, m, deterministic)
}
func (m *BadIP_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIP_JSONPayload.Merge(m, src)
}
func (m *BadIP_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_BadIP_JSONPayload.Size(m)
}
func (m *BadIP_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIP_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_BadIP_JSONPayload proto.InternalMessageInfo

func (m *BadIP_JSONPayload) GetAffectedResources() []*BadIP_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *BadIP_JSONPayload) GetProperties() *BadIP_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BadIP_JSONPayload) GetDetectionCategory() *BadIP_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type SshBruteForce struct {
	InsertId             string                     `protobuf:"bytes,1,opt,name=insertId,proto3" json:"insertId,omitempty"`
	LogName              string                     `protobuf:"bytes,2,opt,name=logName,proto3" json:"logName,omitempty"`
	JsonPayload          *SshBruteForce_JSONPayload `protobuf:"bytes,3,opt,name=jsonPayload,proto3" json:"jsonPayload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SshBruteForce) Reset()         { *m = SshBruteForce{} }
func (m *SshBruteForce) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce) ProtoMessage()    {}
func (*SshBruteForce) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3}
}

func (m *SshBruteForce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce.Unmarshal(m, b)
}
func (m *SshBruteForce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce.Marshal(b, m, deterministic)
}
func (m *SshBruteForce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce.Merge(m, src)
}
func (m *SshBruteForce) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce.Size(m)
}
func (m *SshBruteForce) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce proto.InternalMessageInfo

func (m *SshBruteForce) GetInsertId() string {
	if m != nil {
		return m.InsertId
	}
	return ""
}

func (m *SshBruteForce) GetLogName() string {
	if m != nil {
		return m.LogName
	}
	return ""
}

func (m *SshBruteForce) GetJsonPayload() *SshBruteForce_JSONPayload {
	if m != nil {
		return m.JsonPayload
	}
	return nil
}

type SshBruteForce_LoginAttempt struct {
	AuthResult           string   `protobuf:"bytes,1,opt,name=authResult,proto3" json:"authResult,omitempty"`
	SourceIp             string   `protobuf:"bytes,2,opt,name=sourceIp,proto3" json:"sourceIp,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	VmName               string   `protobuf:"bytes,4,opt,name=vmName,proto3" json:"vmName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_LoginAttempt) Reset()         { *m = SshBruteForce_LoginAttempt{} }
func (m *SshBruteForce_LoginAttempt) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_LoginAttempt) ProtoMessage()    {}
func (*SshBruteForce_LoginAttempt) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 0}
}

func (m *SshBruteForce_LoginAttempt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Unmarshal(m, b)
}
func (m *SshBruteForce_LoginAttempt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_LoginAttempt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_LoginAttempt.Merge(m, src)
}
func (m *SshBruteForce_LoginAttempt) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_LoginAttempt.Size(m)
}
func (m *SshBruteForce_LoginAttempt) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_LoginAttempt.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_LoginAttempt proto.InternalMessageInfo

func (m *SshBruteForce_LoginAttempt) GetAuthResult() string {
	if m != nil {
		return m.AuthResult
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetSourceIp() string {
	if m != nil {
		return m.SourceIp
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SshBruteForce_LoginAttempt) GetVmName() string {
	if m != nil {
		return m.VmName
	}
	return ""
}

type SshBruteForce_Properties struct {
	InstanceId           string                        `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ProjectId            string                        `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Zone                 string                        `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	LoginAttempts        []*SshBruteForce_LoginAttempt `protobuf:"bytes,4,rep,name=LoginAttempts,proto3" json:"LoginAttempts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SshBruteForce_Properties) Reset()         { *m = SshBruteForce_Properties{} }
func (m *SshBruteForce_Properties) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_Properties) ProtoMessage()    {}
func (*SshBruteForce_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 1}
}

func (m *SshBruteForce_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_Properties.Unmarshal(m, b)
}
func (m *SshBruteForce_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_Properties.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_Properties.Merge(m, src)
}
func (m *SshBruteForce_Properties) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_Properties.Size(m)
}
func (m *SshBruteForce_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_Properties proto.InternalMessageInfo

func (m *SshBruteForce_Properties) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *SshBruteForce_Properties) GetZone() string {
	if m != nil {
		return m.Zone
	}
	return ""
}

func (m *SshBruteForce_Properties) GetLoginAttempts() []*SshBruteForce_LoginAttempt {
	if m != nil {
		return m.LoginAttempts
	}
	return nil
}

type SshBruteForce_AffectedResource struct {
	GcpResourceName      string   `protobuf:"bytes,1,opt,name=gcpResourceName,proto3" json:"gcpResourceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_AffectedResource) Reset()         { *m = SshBruteForce_AffectedResource{} }
func (m *SshBruteForce_AffectedResource) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_AffectedResource) ProtoMessage()    {}
func (*SshBruteForce_AffectedResource) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 2}
}

func (m *SshBruteForce_AffectedResource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Unmarshal(m, b)
}
func (m *SshBruteForce_AffectedResource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_AffectedResource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_AffectedResource.Merge(m, src)
}
func (m *SshBruteForce_AffectedResource) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_AffectedResource.Size(m)
}
func (m *SshBruteForce_AffectedResource) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_AffectedResource.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_AffectedResource proto.InternalMessageInfo

func (m *SshBruteForce_AffectedResource) GetGcpResourceName() string {
	if m != nil {
		return m.GcpResourceName
	}
	return ""
}

type SshBruteForce_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SshBruteForce_DetectionCategory) Reset()         { *m = SshBruteForce_DetectionCategory{} }
func (m *SshBruteForce_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_DetectionCategory) ProtoMessage()    {}
func (*SshBruteForce_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 3}
}

func (m *SshBruteForce_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Unmarshal(m, b)
}
func (m *SshBruteForce_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_DetectionCategory.Merge(m, src)
}
func (m *SshBruteForce_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_DetectionCategory.Size(m)
}
func (m *SshBruteForce_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_DetectionCategory proto.InternalMessageInfo

func (m *SshBruteForce_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type SshBruteForce_JSONPayload struct {
	AffectedResources    []*SshBruteForce_AffectedResource `protobuf:"bytes,1,rep,name=affectedResources,proto3" json:"affectedResources,omitempty"`
	Properties           *SshBruteForce_Properties         `protobuf:"bytes,2,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *SshBruteForce_DetectionCategory  `protobuf:"bytes,3,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SshBruteForce_JSONPayload) Reset()         { *m = SshBruteForce_JSONPayload{} }
func (m *SshBruteForce_JSONPayload) String() string { return proto.CompactTextString(m) }
func (*SshBruteForce_JSONPayload) ProtoMessage()    {}
func (*SshBruteForce_JSONPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{3, 4}
}

func (m *SshBruteForce_JSONPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Unmarshal(m, b)
}
func (m *SshBruteForce_JSONPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Marshal(b, m, deterministic)
}
func (m *SshBruteForce_JSONPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SshBruteForce_JSONPayload.Merge(m, src)
}
func (m *SshBruteForce_JSONPayload) XXX_Size() int {
	return xxx_messageInfo_SshBruteForce_JSONPayload.Size(m)
}
func (m *SshBruteForce_JSONPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_SshBruteForce_JSONPayload.DiscardUnknown(m)
}

var xxx_messageInfo_SshBruteForce_JSONPayload proto.InternalMessageInfo

func (m *SshBruteForce_JSONPayload) GetAffectedResources() []*SshBruteForce_AffectedResource {
	if m != nil {
		return m.AffectedResources
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetProperties() *SshBruteForce_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *SshBruteForce_JSONPayload) GetDetectionCategory() *SshBruteForce_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIPSCC struct {
	NotificationConfigName string            `protobuf:"bytes,1,opt,name=notificationConfigName,proto3" json:"notificationConfigName,omitempty"`
	Finding                *BadIPSCC_Finding `protobuf:"bytes,2,opt,name=finding,proto3" json:"finding,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}          `json:"-"`
	XXX_unrecognized       []byte            `json:"-"`
	XXX_sizecache          int32             `json:"-"`
}

func (m *BadIPSCC) Reset()         { *m = BadIPSCC{} }
func (m *BadIPSCC) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC) ProtoMessage()    {}
func (*BadIPSCC) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4}
}

func (m *BadIPSCC) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC.Unmarshal(m, b)
}
func (m *BadIPSCC) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC.Marshal(b, m, deterministic)
}
func (m *BadIPSCC) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC.Merge(m, src)
}
func (m *BadIPSCC) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC.Size(m)
}
func (m *BadIPSCC) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC proto.InternalMessageInfo

func (m *BadIPSCC) GetNotificationConfigName() string {
	if m != nil {
		return m.NotificationConfigName
	}
	return ""
}

func (m *BadIPSCC) GetFinding() *BadIPSCC_Finding {
	if m != nil {
		return m.Finding
	}
	return nil
}

type BadIPSCC_SecurityMarks struct {
	Marks                map[string]string `protobuf:"bytes,1,rep,name=marks,proto3" json:"marks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BadIPSCC_SecurityMarks) Reset()         { *m = BadIPSCC_SecurityMarks{} }
func (m *BadIPSCC_SecurityMarks) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_SecurityMarks) ProtoMessage()    {}
func (*BadIPSCC_SecurityMarks) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 0}
}

func (m *BadIPSCC_SecurityMarks) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Unmarshal(m, b)
}
func (m *BadIPSCC_SecurityMarks) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_SecurityMarks) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_SecurityMarks.Merge(m, src)
}
func (m *BadIPSCC_SecurityMarks) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_SecurityMarks.Size(m)
}
func (m *BadIPSCC_SecurityMarks) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_SecurityMarks.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_SecurityMarks proto.InternalMessageInfo

func (m *BadIPSCC_SecurityMarks) GetMarks() map[string]string {
	if m != nil {
		return m.Marks
	}
	return nil
}

type BadIPSCC_Network struct {
	Project              string   `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIPSCC_Network) Reset()         { *m = BadIPSCC_Network{} }
func (m *BadIPSCC_Network) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Network) ProtoMessage()    {}
func (*BadIPSCC_Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 1}
}

func (m *BadIPSCC_Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Network.Unmarshal(m, b)
}
func (m *BadIPSCC_Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Network.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Network.Merge(m, src)
}
func (m *BadIPSCC_Network) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Network.Size(m)
}
func (m *BadIPSCC_Network) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Network.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Network proto.InternalMessageInfo

func (m *BadIPSCC_Network) GetProject() string {
	if m != nil {
		return m.Project
	}
	return ""
}

func (m *BadIPSCC_Network) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type BadIPSCC_Properties struct {
	Network              *BadIPSCC_Network `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	InstanceDetails      string            `protobuf:"bytes,2,opt,name=instanceDetails,proto3" json:"instanceDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BadIPSCC_Properties) Reset()         { *m = BadIPSCC_Properties{} }
func (m *BadIPSCC_Properties) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Properties) ProtoMessage()    {}
func (*BadIPSCC_Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 2}
}

func (m *BadIPSCC_Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Properties.Unmarshal(m, b)
}
func (m *BadIPSCC_Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Properties.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Properties.Merge(m, src)
}
func (m *BadIPSCC_Properties) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Properties.Size(m)
}
func (m *BadIPSCC_Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Properties proto.InternalMessageInfo

func (m *BadIPSCC_Properties) GetNetwork() *BadIPSCC_Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *BadIPSCC_Properties) GetInstanceDetails() string {
	if m != nil {
		return m.InstanceDetails
	}
	return ""
}

type BadIPSCC_DetectionCategory struct {
	RuleName             string   `protobuf:"bytes,1,opt,name=ruleName,proto3" json:"ruleName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BadIPSCC_DetectionCategory) Reset()         { *m = BadIPSCC_DetectionCategory{} }
func (m *BadIPSCC_DetectionCategory) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_DetectionCategory) ProtoMessage()    {}
func (*BadIPSCC_DetectionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 3}
}

func (m *BadIPSCC_DetectionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Unmarshal(m, b)
}
func (m *BadIPSCC_DetectionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_DetectionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_DetectionCategory.Merge(m, src)
}
func (m *BadIPSCC_DetectionCategory) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_DetectionCategory.Size(m)
}
func (m *BadIPSCC_DetectionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_DetectionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_DetectionCategory proto.InternalMessageInfo

func (m *BadIPSCC_DetectionCategory) GetRuleName() string {
	if m != nil {
		return m.RuleName
	}
	return ""
}

type BadIPSCC_SourceProperties struct {
	Properties           *BadIPSCC_Properties        `protobuf:"bytes,1,opt,name=properties,proto3" json:"properties,omitempty"`
	DetectionCategory    *BadIPSCC_DetectionCategory `protobuf:"bytes,2,opt,name=detectionCategory,proto3" json:"detectionCategory,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BadIPSCC_SourceProperties) Reset()         { *m = BadIPSCC_SourceProperties{} }
func (m *BadIPSCC_SourceProperties) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_SourceProperties) ProtoMessage()    {}
func (*BadIPSCC_SourceProperties) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 4}
}

func (m *BadIPSCC_SourceProperties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Unmarshal(m, b)
}
func (m *BadIPSCC_SourceProperties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_SourceProperties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_SourceProperties.Merge(m, src)
}
func (m *BadIPSCC_SourceProperties) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_SourceProperties.Size(m)
}
func (m *BadIPSCC_SourceProperties) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_SourceProperties.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_SourceProperties proto.InternalMessageInfo

func (m *BadIPSCC_SourceProperties) GetProperties() *BadIPSCC_Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *BadIPSCC_SourceProperties) GetDetectionCategory() *BadIPSCC_DetectionCategory {
	if m != nil {
		return m.DetectionCategory
	}
	return nil
}

type BadIPSCC_Finding struct {
	SourceProperties     *BadIPSCC_SourceProperties `protobuf:"bytes,1,opt,name=sourceProperties,proto3" json:"sourceProperties,omitempty"`
	Category             string                     `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	ResourceName         string                     `protobuf:"bytes,3,opt,name=resourceName,proto3" json:"resourceName,omitempty"`
	State                string                     `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	SecurityMarks        *BadIPSCC_SecurityMarks    `protobuf:"bytes,5,opt,name=securityMarks,proto3" json:"securityMarks,omitempty"`
	EventTime            string                     `protobuf:"bytes,6,opt,name=eventTime,proto3" json:"eventTime,omitempty"`
	Name                 string                     `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *BadIPSCC_Finding) Reset()         { *m = BadIPSCC_Finding{} }
func (m *BadIPSCC_Finding) String() string { return proto.CompactTextString(m) }
func (*BadIPSCC_Finding) ProtoMessage()    {}
func (*BadIPSCC_Finding) Descriptor() ([]byte, []int) {
	return fileDescriptor_7762cc4b80af3525, []int{4, 5}
}

func (m *BadIPSCC_Finding) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BadIPSCC_Finding.Unmarshal(m, b)
}
func (m *BadIPSCC_Finding) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BadIPSCC_Finding.Marshal(b, m, deterministic)
}
func (m *BadIPSCC_Finding) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BadIPSCC_Finding.Merge(m, src)
}
func (m *BadIPSCC_Finding) XXX_Size() int {
	return xxx_messageInfo_BadIPSCC_Finding.Size(m)
}
func (m *BadIPSCC_Finding) XXX_DiscardUnknown() {
	xxx_messageInfo_BadIPSCC_Finding.DiscardUnknown(m)
}

var xxx_messageInfo_BadIPSCC_Finding proto.InternalMessageInfo

func (m *BadIPSCC_Finding) GetSourceProperties() *BadIPSCC_SourceProperties {
	if m != nil {
		return m.SourceProperties
	}
	return nil
}

func (m *BadIPSCC_Finding) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *BadIPSCC_Finding) GetResourceName() string {
	if m != nil {
		return m.ResourceName
	}
	return ""
}

func (m *BadIPSCC_Finding) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *BadIPSCC_Finding) GetSecurityMarks() *BadIPSCC_SecurityMarks {
	if m != nil {
		return m.SecurityMarks
	}
	return nil
}

func (m *BadIPSCC_Finding) GetEventTime() string {
	if m != nil {
		return m.EventTime
	}
	return ""
}

func (m *BadIPSCC_Finding) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*BadDomain)(nil), "BadDomain")
	proto.RegisterType((*AnomalousIAMGrant)(nil), "AnomalousIAMGrant")
	proto.RegisterType((*AnomalousIAMGrant_Properties)(nil), "AnomalousIAMGrant.Properties")
	proto.RegisterType((*AnomalousIAMGrant_AffectedResource)(nil), "AnomalousIAMGrant.AffectedResource")
	proto.RegisterType((*AnomalousIAMGrant_DetectionCategory)(nil), "AnomalousIAMGrant.DetectionCategory")
	proto.RegisterType((*AnomalousIAMGrant_JSONPayload)(nil), "AnomalousIAMGrant.JSONPayload")
	proto.RegisterType((*BadIP)(nil), "BadIP")
	proto.RegisterType((*BadIP_Properties)(nil), "BadIP.Properties")
	proto.RegisterType((*BadIP_AffectedResource)(nil), "BadIP.AffectedResource")
	proto.RegisterType((*BadIP_DetectionCategory)(nil), "BadIP.DetectionCategory")
	proto.RegisterType((*BadIP_JSONPayload)(nil), "BadIP.JSONPayload")
	proto.RegisterType((*SshBruteForce)(nil), "SshBruteForce")
	proto.RegisterType((*SshBruteForce_LoginAttempt)(nil), "SshBruteForce.LoginAttempt")
	proto.RegisterType((*SshBruteForce_Properties)(nil), "SshBruteForce.Properties")
	proto.RegisterType((*SshBruteForce_AffectedResource)(nil), "SshBruteForce.AffectedResource")
	proto.RegisterType((*SshBruteForce_DetectionCategory)(nil), "SshBruteForce.DetectionCategory")
	proto.RegisterType((*SshBruteForce_JSONPayload)(nil), "SshBruteForce.JSONPayload")
	proto.RegisterType((*BadIPSCC)(nil), "BadIPSCC")
	proto.RegisterType((*BadIPSCC_SecurityMarks)(nil), "BadIPSCC.SecurityMarks")
	proto.RegisterMapType((map[string]string)(nil), "BadIPSCC.SecurityMarks.MarksEntry")
	proto.RegisterType((*BadIPSCC_Network)(nil), "BadIPSCC.Network")
	proto.RegisterType((*BadIPSCC_Properties)(nil), "BadIPSCC.Properties")
	proto.RegisterType((*BadIPSCC_DetectionCategory)(nil), "BadIPSCC.DetectionCategory")
	proto.RegisterType((*BadIPSCC_SourceProperties)(nil), "BadIPSCC.SourceProperties")
	proto.RegisterType((*BadIPSCC_Finding)(nil), "BadIPSCC.Finding")
}

func init() { proto.RegisterFile("etd/protos/etd.proto", fileDescriptor_7762cc4b80af3525) }

var fileDescriptor_7762cc4b80af3525 = []byte{
	// 933 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x96, 0xdf, 0x6e, 0x1b, 0xc5,
	0x17, 0xc7, 0xe5, 0x3f, 0xb1, 0xe3, 0xe3, 0x46, 0xbf, 0x78, 0x14, 0xb5, 0xfb, 0xdb, 0xd2, 0xd6,
	0x32, 0x5c, 0x58, 0x54, 0x72, 0x44, 0xa8, 0x50, 0x40, 0xad, 0xc0, 0x71, 0x1a, 0x64, 0x44, 0x42,
	0x3a, 0x86, 0xeb, 0x6a, 0xb2, 0x3b, 0x76, 0xb7, 0x59, 0xcf, 0x58, 0x33, 0xb3, 0x01, 0x73, 0xc1,
	0x05, 0x88, 0x27, 0xe0, 0x86, 0x7b, 0x5e, 0x83, 0x77, 0xe0, 0x31, 0x10, 0xd7, 0x5c, 0x23, 0xa1,
	0x9d, 0x99, 0xb5, 0x77, 0xd7, 0xbb, 0xc8, 0x29, 0x12, 0x37, 0xd1, 0x9c, 0x33, 0x73, 0x8e, 0xbf,
	0xf3, 0xdd, 0xcf, 0x1c, 0x05, 0x0e, 0xa8, 0xf2, 0x0f, 0x17, 0x82, 0x2b, 0x2e, 0x0f, 0xa9, 0xf2,
	0x07, 0x7a, 0xd9, 0x7b, 0x17, 0x5a, 0x27, 0xc4, 0x3f, 0xe5, 0x73, 0x12, 0x30, 0xf4, 0x00, 0x20,
	0x58, 0xbc, 0x24, 0xbe, 0x2f, 0xa8, 0x94, 0x4e, 0xa5, 0x5b, 0xe9, 0xb7, 0x70, 0x2b, 0x58, 0x0c,
	0x4d, 0xa2, 0xf7, 0x47, 0x1d, 0x3a, 0x43, 0xc6, 0xe7, 0x24, 0xe4, 0x91, 0x1c, 0x0f, 0xcf, 0x3f,
	0x15, 0x84, 0x29, 0xe4, 0xc2, 0x6e, 0xc0, 0x24, 0x15, 0x6a, 0xec, 0xdb, 0x92, 0x55, 0x8c, 0x1c,
	0x68, 0x86, 0x7c, 0x76, 0x41, 0xe6, 0xd4, 0xa9, 0xea, 0xad, 0x24, 0x44, 0x9f, 0x40, 0xfb, 0xb5,
	0xe4, 0xec, 0x92, 0x2c, 0x43, 0x4e, 0x7c, 0xa7, 0xd6, 0xad, 0xf4, 0xdb, 0x47, 0x0f, 0x07, 0x1b,
	0xed, 0x07, 0x9f, 0x4d, 0xbe, 0xb8, 0xb0, 0xa7, 0x70, 0xba, 0xc4, 0xfd, 0x0a, 0xe0, 0x52, 0xf0,
	0x05, 0x15, 0x2a, 0xa0, 0x32, 0x96, 0xbe, 0x10, 0xfc, 0x35, 0xf5, 0xd4, 0xcb, 0x20, 0xd1, 0xd1,
	0xb2, 0x99, 0xb1, 0x8f, 0xfa, 0xf0, 0x3f, 0xfa, 0x8d, 0xa2, 0x82, 0x91, 0xf0, 0x9c, 0xce, 0xaf,
	0xa8, 0x90, 0x4e, 0xb5, 0x5b, 0xeb, 0xb7, 0x70, 0x3e, 0xed, 0x3e, 0x85, 0xfd, 0xe1, 0x74, 0x4a,
	0x3d, 0x45, 0x7d, 0x4c, 0x25, 0x8f, 0x84, 0x47, 0xe3, 0xea, 0x99, 0xb7, 0x48, 0x42, 0x7d, 0x1d,
	0xf3, 0x0b, 0xf9, 0xb4, 0xfb, 0x02, 0x3a, 0xa7, 0x54, 0x51, 0x4f, 0x05, 0x9c, 0x8d, 0x88, 0xa2,
	0x33, 0x2e, 0x96, 0xb1, 0x43, 0x22, 0x0a, 0xd3, 0x75, 0xab, 0x18, 0x75, 0xa1, 0x2d, 0xa3, 0x2b,
	0x9c, 0x6c, 0x1b, 0x97, 0xd2, 0x29, 0xf7, 0xcf, 0x0a, 0xb4, 0x53, 0x26, 0xa0, 0x17, 0xd0, 0x21,
	0x39, 0x81, 0xf1, 0xb7, 0xaa, 0xf5, 0xdb, 0x47, 0x6f, 0x17, 0xf8, 0x97, 0xbf, 0x0c, 0xde, 0xac,
	0x46, 0xcf, 0xb4, 0x79, 0xd6, 0x4a, 0xad, 0xa1, 0x7d, 0xf4, 0xa0, 0xa0, 0xd7, 0xda, 0x6f, 0x9c,
	0x2a, 0x40, 0x18, 0x3a, 0x7e, 0xfe, 0xd2, 0xf6, 0x8b, 0xbe, 0x53, 0xd0, 0x65, 0xc3, 0x20, 0xbc,
	0x59, 0xde, 0xfb, 0xb5, 0x0e, 0x3b, 0x27, 0xc4, 0x1f, 0x5f, 0xbe, 0x21, 0x5f, 0x4f, 0x8a, 0xf8,
	0x42, 0x03, 0xdd, 0xb2, 0x9c, 0xa9, 0x1f, 0x2b, 0xb7, 0x81, 0xca, 0x85, 0xdd, 0x90, 0x7b, 0x24,
	0xd6, 0x6d, 0x7f, 0x7e, 0x15, 0xc7, 0xc8, 0x04, 0x4c, 0x2a, 0xc2, 0x3c, 0x7a, 0x4a, 0x15, 0x09,
	0x42, 0xa9, 0x35, 0xb4, 0x70, 0x3e, 0x8d, 0x10, 0xd4, 0xbf, 0xe5, 0x8c, 0x3a, 0x75, 0xbd, 0xad,
	0xd7, 0xff, 0x12, 0xc2, 0xc3, 0x5b, 0x42, 0xe8, 0xfe, 0x96, 0x43, 0xec, 0x79, 0x39, 0x62, 0xf7,
	0xac, 0x85, 0xdb, 0x60, 0xf5, 0x5e, 0x01, 0x56, 0x1d, 0x5b, 0x5f, 0x82, 0xd2, 0x59, 0x39, 0x4a,
	0x8e, 0xad, 0xdc, 0x0a, 0x9f, 0xef, 0x1b, 0xb0, 0x37, 0x91, 0xaf, 0x4e, 0x44, 0xa4, 0xe8, 0x19,
	0x8f, 0xed, 0x7b, 0x33, 0x8c, 0x9e, 0x16, 0x61, 0xe4, 0x0e, 0x32, 0xad, 0xcb, 0x71, 0xfa, 0x0e,
	0xee, 0x7c, 0xce, 0x67, 0x01, 0x1b, 0x2a, 0x45, 0xe7, 0x0b, 0x85, 0x1e, 0x02, 0x90, 0x48, 0xbd,
	0xc2, 0x54, 0x46, 0xa1, 0xb2, 0x2a, 0x52, 0x99, 0x58, 0xa3, 0xf1, 0x6e, 0xbc, 0x48, 0x80, 0x4a,
	0xe2, 0x78, 0x2f, 0x92, 0x54, 0x68, 0x91, 0x86, 0xa4, 0x55, 0x8c, 0xee, 0x42, 0xe3, 0x66, 0xae,
	0x77, 0x0c, 0x44, 0x36, 0x72, 0x7f, 0xc9, 0xe2, 0xfc, 0x08, 0xda, 0x09, 0x7c, 0x6b, 0x9e, 0x21,
	0x49, 0x8d, 0xfd, 0x1c, 0xef, 0xd5, 0x3c, 0xef, 0x09, 0xa9, 0xb5, 0x35, 0xa9, 0x68, 0x08, 0x7b,
	0xe9, 0x2b, 0x4a, 0xa7, 0xae, 0x31, 0xb9, 0x9f, 0xb3, 0x28, 0x7d, 0x06, 0x67, 0x2b, 0xfe, 0x6b,
	0xd8, 0x7f, 0xcf, 0xc1, 0x7e, 0x5e, 0x0e, 0xfb, 0xa3, 0xdc, 0x2d, 0xb6, 0x81, 0xfe, 0xc3, 0x02,
	0xe8, 0xff, 0x9f, 0xeb, 0x53, 0x02, 0xff, 0x45, 0x39, 0xfc, 0xdd, 0x5c, 0x87, 0xad, 0x1e, 0xc1,
	0x5f, 0x0d, 0xd8, 0xd5, 0x6f, 0x66, 0x32, 0x1a, 0xa1, 0x0f, 0xe0, 0x2e, 0xe3, 0x2a, 0x98, 0x06,
	0x66, 0x40, 0x8d, 0x38, 0x9b, 0x06, 0xb3, 0x94, 0x41, 0x25, 0xbb, 0xe8, 0x31, 0x34, 0xa7, 0x01,
	0xf3, 0x03, 0x36, 0xcb, 0xbe, 0xe0, 0xc9, 0x68, 0x34, 0x38, 0x33, 0x1b, 0x38, 0x39, 0xe1, 0xfe,
	0x50, 0x81, 0xbd, 0x09, 0xf5, 0x22, 0x11, 0xa8, 0xe5, 0x39, 0x11, 0xd7, 0x12, 0x1d, 0xc3, 0xce,
	0x3c, 0x5e, 0x58, 0x47, 0x7b, 0xeb, 0xe2, 0xcc, 0xb9, 0x81, 0xfe, 0xfb, 0x9c, 0x29, 0xb1, 0xc4,
	0xa6, 0xc0, 0x3d, 0x06, 0x58, 0x27, 0xd1, 0x3e, 0xd4, 0xae, 0xe9, 0xd2, 0x6a, 0x8d, 0x97, 0xe8,
	0x00, 0x76, 0x6e, 0x48, 0x18, 0x25, 0x4f, 0xd6, 0x04, 0x1f, 0x55, 0x8f, 0x2b, 0xee, 0xc7, 0xd0,
	0xbc, 0xa0, 0xea, 0x6b, 0x2e, 0xae, 0xe3, 0x97, 0x6d, 0xf9, 0xb5, 0xa5, 0x49, 0xf8, 0x4f, 0xc3,
	0xdb, 0xf5, 0x32, 0xcf, 0xe6, 0x31, 0x34, 0x99, 0x69, 0xa7, 0x7b, 0x64, 0x1c, 0xb0, 0xbf, 0x83,
	0x93, 0x13, 0x45, 0x73, 0xbf, 0x5a, 0x38, 0xf7, 0x6f, 0x0f, 0xee, 0x4f, 0x15, 0xd8, 0x9f, 0x68,
	0xca, 0x52, 0xe2, 0x9e, 0x64, 0x70, 0x33, 0xfa, 0x0e, 0xd6, 0xfa, 0x4a, 0x48, 0x1b, 0x17, 0x91,
	0x66, 0x3e, 0xef, 0xfd, 0x75, 0xf1, 0x36, 0x90, 0xb9, 0x3f, 0x57, 0xa1, 0x69, 0x39, 0x40, 0x67,
	0xb0, 0x2f, 0x73, 0x02, 0xad, 0x24, 0x37, 0xf5, 0xdd, 0x73, 0x27, 0xf0, 0x46, 0x4d, 0xec, 0x82,
	0x97, 0x56, 0xd5, 0xc2, 0xab, 0x18, 0xf5, 0xe0, 0x8e, 0x48, 0x8f, 0x05, 0x33, 0x8c, 0x32, 0xb9,
	0x18, 0x0d, 0xa9, 0x88, 0x4a, 0xc6, 0xa1, 0x09, 0xd0, 0x33, 0xd8, 0x93, 0x69, 0xe6, 0x9c, 0x1d,
	0x2d, 0xed, 0x5e, 0x09, 0x92, 0x38, 0x7b, 0x1a, 0xbd, 0x05, 0x2d, 0x7a, 0x43, 0x99, 0xfa, 0x32,
	0x98, 0x53, 0xa7, 0x61, 0x66, 0xe3, 0x2a, 0x11, 0xcf, 0x46, 0x16, 0xcb, 0x69, 0x9a, 0xd9, 0x18,
	0xaf, 0xaf, 0x1a, 0xfa, 0x5f, 0xec, 0xf7, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x70, 0x32, 0xb0,
	0x5c, 0x7a, 0x0b, 0x00, 0x00,
}
