apiVersion: security-response-automation.cloud.google.com/v1alpha1
kind: RemediationFunction
metadata:
  name: iam_revoke
spec:
  match:
    target:
      - organization/*
    exclude:
      - folder/123
      - project/456
  validation:
    openAPIV3Schema:
      properties:
        dry_run: false
        allow_domains:
          - gmail.com
